### ISSUE TITLE
claudia update leads to XMLParserError: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by RudthMael** [claudiajs/claudia#10]
Hi,

I created a lambda function + api gateway bound to it.
Here is the json file created:
```json
{
  "lambda": {
    "role": "foobar_execution",
    "name": "foobar",
    "region": "us-east-1"
  },
  "api": {
    "id": "qmmx2fe229",
    "module": "src/server.js"
  }
}
```

When I run `claudia update` to push some new code, I get this:

```
{ [XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: {]
  cause:
   { [XMLParserError: Non-whitespace before first tag.
   Line: 0
   Column: 1
   Char: {]
     message: 'Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: {',
     code: 'XMLParserError',
     retryable: true,
     time: Fri Feb 26 2016 14:46:02 GMT+0100 (CET),
     statusCode: 500 },
  isOperational: true,
  code: 'XMLParserError',
  retryable: true,
  time: Fri Feb 26 2016 14:46:02 GMT+0100 (CET),
  statusCode: 500 }
```

Am I doing something wrong?

**Comment by gojko** [comment]
I have no idea what this is, Claudia is not using XML anywhere, so I wouldn't expect XML processing to kick off at all. It might be that something inside API gateway gets triggered by a particular content edge case. 

Is there a stack trace associated with this message? Can you create a minimal project that shows the error and share it, so I can try to reproduce it?

**Comment by RudthMael** [comment]
I saved claudia in the node_modules folder instead of globally.
Maybe it's a version mismatch:

```
$ which claudia
=> /Users/me/.nvm/v0.10.36/bin/claudia
```
This one works.

If it's saved in the node_modules:
```
$ which claudia
=> /foo/bar/baz/node_modules/.bin/claudia
```
This one does not work.

**Comment by gojko** [comment]
ok, so that's something with the local setup then. I'll close the issue in that case
