### ISSUE TITLE
Separate Lambda Function for Single API

### ISSUE THREAD

**Issue by harshaldavda** [claudiajs/claudia#102]
Hi.. I want to create separate Lambda function for my each file. but need to create only 1 API in AWS. so, each Lambda Function can be connected with "Resource" in API.

i.e. 
{url}/file1
{url}/file2
{url}/file3

I don't want new url and new api_id for each lambda function. I want something like above example.
Is it possible using Claudia???

**Comment by gojko** [comment]
hi, 

please use the gitter chat channel for chat, we use github issues only for bugs
