### ISSUE TITLE
claudia destroy throws error if I have a Custom Domain Name

### ISSUE THREAD

**Issue by stevemao** [claudiajs/claudia#113]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

I know this is expected. And the error message is helpful 😄 

I think we could introduce a `--force` flag to also remove the Custom Domain Name. Or friendly print out a command to remove the Custom Domain Name.

---

* Expected behaviour:

* What actually happens:

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by gojko** [comment]
this is not a bug. please use the gitter channel for feature ideas
