### ISSUE TITLE
claudia destroy fails if lambda function doesn't exist

### ISSUE THREAD

**Issue by stevemao** [claudiajs/claudia#114]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

Because of https://github.com/claudiajs/claudia/issues/113, When I run `claudia destroy`, it destroys my lambda function first, then attempt to destroy the api gateway resources. However it fails because of my custom domain. So I manually removed my custom domain name and run `claudia destroy`. It then fails because I don't have the lambda function. It should destroy the remaining resources regardless of the lambda function.

---

* Expected behaviour:

It shouldn't error if I don't have the lambda function anymore

* What actually happens:

It errors and exits, and I have to manually cleanup everything.

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

`claudia create`, then manually remove the lambda function. Then `claudia destroy`

**Comment by gojko** [comment]
this works as described -- it needs to error if people try to delete a non-existing function, so it's not a bug
