### ISSUE TITLE
gzip compression error

### ISSUE THREAD

**Issue by anieve01** [claudiajs/claudia#119]
hello. the guys doing aws-serverless-express have added supported for gzip compression and have indicated how to enable it in the swagger yaml file (see https://github.com/awslabs/aws-serverless-express/pull/51/files/4d54a81b831eca97524f15b72fa8be379c80aedb).  However, I can't seem to find a way to tell claudia to enable the gzip compression option.  I've already added binaryMediaTypes in lambda.js but I see how to add binaryMediaTypes to the api gateway's binaryMediaTypes as specified in the link. any example with code on how to enable this in claudia. Thanks

**Comment by gojko** [comment]
please use github issues only to report bugs. see https://github.com/claudiajs/claudia/blob/master/contributing.md for info on where to ask questions
