### ISSUE TITLE
Convert periods to underscore when creating event source

### ISSUE THREAD

**Issue by jborseth** [claudiajs/claudia#123]
Attempting to add an event source to a bucket where the bucket name contains a period will fail due to the period being an invalid character.

This is important because to use Cloudflare with S3, Cloudflare requires an exact match domain such as `cdn.mydomain.com`. 

---

**Expected behaviour:**

Event should be created successfully. 

**What actually happens:** 

The following error message occurs:
`ValidationException: 1 validation error detected: Value 'cdn.mydomain.com-access' at 'statementId' failed to satisfy constraint: Member must satisfy regular expression pattern: ([a-zA-Z0-9-_]+)`

**Steps to reproduce the problem:**

1. Create a bucket with a name containing a period: cdn.mydomain.com
2. Run: `claudia add-s3-event-source --bucket cdn.mydomain.com --prefix in/`

**Suggested solution**

I'd suggest automatically converting periods when creating the event to underscores given the underscore is considered a valid character.

**Comment by gojko** [comment]
what version of claudia are you using? this should already work as described. (eg this should have been fixed already with https://github.com/claudiajs/claudia/commit/80d7693c68cc270c13da86fcb74d05a644b7ce03)

**Comment by jborseth** [comment]
Let me test again. I did discover that Claudia 1.x was downloaded by default and I updated to 2.x to solve another issue. Will try this again and reopen if necessary. Thanks!
