### ISSUE TITLE
api set-env option problem

### ISSUE THREAD

**Issue by dale-paul** [claudiajs/claudia#125]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour:

When calling create in NodeJS as:
```
claudia.create({
   setEnv: 'variable1=value1'
})
```
The lambda environment variables are not set. When calling as:
```
claudia.create({
   'set-env': 'variable1=value1'
})
```
The lambda variables are created as expected.

Per your response in issue #14, command line options such as --set-env where to be converted to camel case such as setEnv. All command line options work this way except this one.

Thanks

**Comment by gojko** [comment]
Hi,

Camel case is only for commands, options are same as in the command line, just without the dashes.
