### ISSUE TITLE
ES6 export syntax not supported in transpiled handler

### ISSUE THREAD

**Issue by lrettig** [claudiajs/claudia#128]
* Expected behaviour: I can write my handler script using ES6 syntax, transpile it (along the lines discussed in #19), and then deploy using claudia

* What actually happens: If I use the ES6 `export` syntax in my handler, `validatePackage` fails because it can't find the module's `proxyRouter` property, causing `claudia update` to fail with: `handler.js does not export a Claudia API Builder instance`

* Link to a minimal, executable project that demonstrates the problem:

```
import ApiBuilder from 'claudia-api-builder';
export const api = new ApiBuilder();
```

This transpiles to:

```
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
var _claudiaApiBuilder = require('claudia-api-builder');
var _claudiaApiBuilder2 = _interopRequireDefault(_claudiaApiBuilder);
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.api = undefined;
var api = exports.api = new _claudiaApiBuilder2.default();
```

* Steps to reproduce the problem:

The error is produced in `validate-package.js` here:

```
	try {
		apiModule = require(path.join(dir, apiModulePath));
	} catch (e) {
		console.error(e.stack || e);
		throw `cannot require ./${apiModulePath} after clean installation. Check your dependencies.`;
	}
	if (!apiModule[handlerMethod]) {
		if (restApiModule) {
			throw `${apiModulePath}.js does not export a Claudia API Builder instance`;
		} else {
			throw `${apiModulePath}.js does not export method ${handlerMethod}`;
		}
	}
```

I guess it's happening because of the dynamic require. Is there any way to make this work with ES6-style import/export?

Thanks!

**Comment by gojko** [comment]
Hi,

it looks as if your transpiled code is not exporting the api directly, but exporting an object with the property `api` (exports.api = ....). This is a bug in the transpiler, not the way how claudia loads things.

**Comment by gojko** [comment]
because AWS Lambda still works with Node 6, not node 8, perhaps you can target the transpiler to produce Node 6 compatible-code?

**Comment by lrettig** [comment]
For the record I'm using babel, which is the most popular/common transpiler, with the following in my `.babelrc`:

```
{"presets": ["es2015", "es2016", "es2017"]}
```

So, nothing fancy or beyond the ordinary going on. I'm not sure how to ask babel to target node 6 compatible code.

It looks like right now dynamic imports [using ES6-style import/export are not possible](https://stackoverflow.com/questions/29168433/es6-variable-import-name-in-node-js?noredirect=1&lq=1) but they [may be possible in the future](https://github.com/tc39/proposal-dynamic-import). I guess there's nothing to be done here, but it's a little annoying that I have to modify my otherwise ES6 code to work with claudia (in practice, using `module.exports = api` works).

Thanks :)

**Comment by lrettig** [comment]
Do you think it might be worth making a note of this on https://claudiajs.com/tutorials/using-babel.html?

**Comment by Aubtin** [comment]
This still seems to be an "issue" in version 5.0.1 building towards Node 8.10 using Babel 7.
