### ISSUE TITLE
Security: Hide Enviroment section from AWS output

### ISSUE THREAD

**Issue by drazisil** [claudiajs/claudia#129]
### Expected behavior:

Secrets not leaked.

### What actually happens:

Secrets leaked.

### Link to a minimal, executable project that demonstrates the problem:

Any project that has security credentials in the environmental variables in AWS Lambda.

### Steps to reproduce the problem:

Update a project with secrets in the environmental variables in AWS Lambda.
The result from AWS will expose the secrets

### Details

```
  "Environment": {
    "Variables": {
      "GITHUB_SECRET": "49301f4c84b5d40fa89c",
      "TOKEN": "35addaccdec5f416da429092d76f7d9769c25d5a",
      "TOKEN_SECRET": "66567e2f16a827a7f7f85b8e999ad75d49bca7a2"
    }
  },
```

The above tokens have been rotated (and changed in the example), but this information would be leaked in any public CI build using Claudia that has secrets in the Lambda settings.

If you must output this section and can't restrict it, at least make it very clear to users that they will expose secrets.

**Comment by gojko** [comment]
thanks. install 2.14.2 and you'll be able to use `--quiet` to suppress output (including env vars)

**Comment by pkyeck** [comment]
Hi, I know that this is an old issue but I think the `--quiet` flag doesn't solve the problem completely. What if we want output but just not the sensitive part in the env vars?
