### ISSUE TITLE
Building local Jasmine test for the Image-Server example

### ISSUE THREAD

**Issue by kktam** [claudiajs/claudia#130]
This is not a bug report, but a question to extend on [issue 4](https://github.com/claudiajs/claudia/issues/4)

In Issue 4, an example page is provided to illustrate how to test locally.
(https://claudiajs.com/tutorials/testing-locally.html)

I am using this information to try to make unit test for the [Image Server example](https://claudiajs.com/tutorials/image-server.html)

In my jasmine test file, I follow the test pattern in your tutorial , but non sure how to use lambdaContextSpy to say get the SVG output and inspect the output.

the jasmine test is located at 
[test file](https://github.com/kktam/repolabels/blob/jasmine/spec/api-spec.js)

---

* Expected behaviour:

* What actually happens:

* Link to a minimal, executable project that demonstrates the problem:

[demo project with jasmine test](https://github.com/kktam/repolabels/tree/jasmine)

* Steps to install the project:

```
git clone https://github.com/kktam/repolabels
git checkout jasmine
npm i 
npm run test
```

* Steps to reproduce the problem:

The test will fail now. Need help in documentation of lambdaContext and lambdaContextSpy to perform getting the api.get() SVG output, return status, counting number of calls etc.

**Comment by gojko** [comment]
please use github issues for bugs only. we have a gitter channel for discussions
