### ISSUE TITLE
Clarification for including and excluding files from deployment.

### ISSUE THREAD

**Issue by gnarf** [claudiajs/claudia#134]
This isn't really a bug, but I'm not sure where I should report this. I can't find a repository/tracker for website content, so if you could please forward this to the appropriate place, I'd much appreciate it! ❤️ 

The [INCLUDING AND EXCLUDING FILES FROM DEPLOYMENT](https://claudiajs.com/tutorials/packaging.html) page on the website states currently:

>Claudia uses the standard Node.js packaging model, so if you’re used to NPM, things will just work out of the box:
> all the standard patterns ignored by NPM are ignored by Claudia as well (including .git, .hg and so on)
> * if .gitignore or .npmignore exist, patterns listed in those files will be excluded
> * if the package.json file includes the files property, only those patterns will be included. See the files section of the NPM configuration guide for more information.
> * all NPM workflow steps (such as post-install) will be executed as during a normal installation, so you can script additional tasks such as transpilation easily.
>
> It’s a good practice, although not necessary, to explicitly list the files or file patterns you want to deploy in the files property of package.json. This will ensure you avoid deploying test and development resources and local configuration files. You do not have to list package.json here, it will automatically be included.

I feel that there are a few inconsistencies here that you should definitely call out.

* [ ] Maybe state that it uses `npm pack` so you can use that to see what would be included
* [ ] **If `.gitignore` or `.npmignore` exist, patterns listed in those files will be excluded** -- This is very misleading... If `.npmignore` exists, it uses this file to get it's excludes even if `.gitignore` exists, this means you can list files in `.gitignore` but not include them in `.npmignore` if you want files to be deployed, but not committed to the repo.

**Comment by simalexan** [comment]
@gnarf Hi!
Thank you for pointing this out, we saw it and will see to clarify. Its already forwarded.
Thank you again!

**Comment by gnarf** [comment]
I just checked the page and it seems to still say the same thing, is there
another issue open I can track?

**Comment by gojko** [comment]
i've left a note that npm pack is executed, and I think the wording is not misleading at all. we can't explain how npm pack works in detail on that page, people should go and learn about npm pack if they need those edge cases

**Comment by gnarf** [comment]
Ah yes, this helps a lot...  Thanks!

**Comment by daliu** [comment]
Took me a while to find this information. Might actually be helpful to just have a small warning section or something.
