### ISSUE TITLE
Programmatic API ?

### ISSUE THREAD

**Issue by Autarc** [claudiajs/claudia#14]
To integrate `claudia` into a project (which already has some tasks like Babel for processing files) it would be useful to access the different functions of the CLI tool directly in node. What do you think about exporting the different calls from the module instead of just the shell runtime ?

```js
import { create as createLambda } from 'claudia'

createLambda(/** params **/).then(() => { .... })
```

Since these setup helpers contain the actual logic for working with AWS lambda & API gateway, the commandline interface could either be a different repository or check the `process` for its callee.

**Comment by gojko** [comment]
that's already there, just not fully documented. each command of the CLI is also exported as a method, so you can, for example, do:

```javascript
var claudia = require('claudia');
claudia.create({name: 'lambda-function', version: 'development', 'api-module': 'web-api', region: 'us-east-1'})
```

instead of dashes, the methods are camel-cased (so `test-lambda` CLI corresponds to `testLambda` in Javascript); the options are the same, just without double-dashes, so instead of `--name`, the use `name`.

this is stable and 100% supported, my plan is to use it for grunt/gulp integration in the future, so you can rely on that API. I will document it soon.

**Comment by TechDecaf** [comment]
I am deploying quite a bit of `claudia` these days and am using gulp for my deployment tasks, however it appears that the `profile` parameter is being passed correctly when I run from node.  Is there a way for me to inject a custom AWS object with my config?

something like: 
``` javascript 
let AWS = require("aws-sdk")
     AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: args.profile})
let claudia = require("claudia")(AWS);
```
**OR**
```
let AWS = require("aws-sdk")
     AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: args.profile})
let claudia = require("claudia");

claudia.create(params, AWS)
   .then((res) => {
            console.info(res);
        })
        .catch((err) => {
            console.error(err);
        });
```

**Comment by gojko** [comment]
this should do the trick, you don't need to pass anything into the commands: https://github.com/claudiajs/claudia/blob/cef25fa62fffa9834463b6a449a0ceb82c401baa/bin/cmd.js#L47

**Comment by WardJon** [comment]
👍  that does work, thanks @gojko

**Comment by JordanPrinceT** [comment]
When I do something like this 
`claudia.create({"region": "us-west-2", "apiModule": "bot", "useLocalDependencies": "true"})`

I have this error : 

> It failed with Lambda handler is missing. please specify with --handler

In documentation, having api-module doesn't require handler. Any idea how to fix this?

I'm also not sure how to use CLI options that has no value like `--use-local-dependencies`

**Comment by gojko** [comment]
you need 'api-module', not 'apiModule'.

**Comment by JordanPrinceT** [comment]
@gojko It works! CamelCase only for method and not for options, my error! Thanks a lot :+1:
