### ISSUE TITLE
claudia create with an existing IAM Role ARN fails for VPC deployments without `iam:PutRolePolicy` permission

### ISSUE THREAD

**Issue by blueimp** [claudiajs/claudia#140]
## Bug report
* Expected behaviour:
The following command creates a new lambda function running in a VPC with the given example IAM role, without the user having `iam:PutRolePolicy` permission:

```sh
claudia create \
  --security-group-ids sg-xxxxxxxx \
  --subnet-ids subnet-xxxxxxxx \
  --role arn:aws:iam::xxxxxxxxxxxx:role/example-role \
  --region eu-west-1
```

* What actually happens:
claudia fails the deployment with the following error message:

```
ValidationError: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
```

* Link to a minimal, executable project that demonstrates the problem:
Any minimal project will do.

* Steps to install the project:
https://claudiajs.com/tutorials/hello-world-lambda.html

* Steps to reproduce the problem:
See "Expected behavior" above.

## Possible solution:
Patching the following two lines (second one is the same issue related to recursion):
https://github.com/claudiajs/claudia/blob/master/src/commands/create.js#L394
https://github.com/claudiajs/claudia/blob/master/src/commands/create.js#L403

Adding a test for `!isRoleArn(options.role)` fixes the issue.

Sample patch code:

```js
	.then(() => {
		if (options['security-group-ids'] && !isRoleArn(options.role)) {
			return iam.putRolePolicy({
				RoleName: roleMetadata.Role.RoleName,
				PolicyName: 'vpc-access-execution',
				PolicyDocument: vpcPolicy()
			}).promise();
		}
	})
	.then(() => {
		if (options['allow-recursion'] && !isRoleArn(options.role)) {
			return iam.putRolePolicy({
				RoleName: roleMetadata.Role.RoleName,
				PolicyName: 'recursive-execution',
				PolicyDocument: recursivePolicy(functionName)
			}).promise();
		}
	})
```

**Comment by gojko** [comment]
thanks, this sounds as a good solution, I'll put it into the next version coming after the new year.

**Comment by blueimp** [comment]
Thanks @gojko !

**Comment by gojko** [comment]
i've implemented the suggested solution for vpc. 

allow recursion now complains if role is specified as an ARN, I think this is more correct because ARN roles should not be touched by claudia, so asking it to both ignore the role setup and configure the role is likely an invalid request

**Comment by gojko** [comment]
this is now on NPM, as v3.0.0
