### ISSUE TITLE
Existing resources on Api Gateway were removed by new ApiBuilder resource.

### ISSUE THREAD

**Issue by MEGApixel23** [claudiajs/claudia#141]
I'm using Api Gateway to configure endpoints which are using different lambdas. When I added new resource, "stores" for example, and built new microservice with using claudia api builder all my old resources got wiped out. 

How can I add a new resource to Api Gateway without affecting existing ones?

**Comment by stojanovic** [comment]
You can't with Claudia API Builder. It is created to help you build small APIs, and it connects API Gateway to a single Lambda function.

If you want to manage multiple lambda functions, probably the best way to do that is by using CloudFormation (or some of the frameworks that uses CF). Alternative is to just deploy plain Lambda functions using Claudia and then manage API Gateway on your own.

**Comment by MEGApixel23** [comment]
Maybe there is some workaround? So for example set up "parent" resource for the builder so it's allowed to make its magic only inside this resource?

**Comment by gojko** [comment]
this is outside the scope of what claudia api builder does now.
