### ISSUE TITLE
Alexa skill: The skill end-point is not validating the signatures for incoming requests and is accepting requests with an empty signature URL.

### ISSUE THREAD

**Issue by isabelacmor** [claudiajs/claudia#143]
We're using Claudia.js to deploy a lambda function for an Alexa skill. Everything works on their platform after running `claudia update` locally, but when we submit the skill for certification, it fails and says:

> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an empty signature URL. Please check if your signature validation is correct. To reject an invalid request (with an invalid signature or certificate), the skill should respond with an HTTP status code 400 (Bad Request). Please refer to our documentation on how to build your Alexa Skill as a web service and validate requests and signatures.

* Link to a minimal, executable project that demonstrates the problem:
Our skill's repo: [https://github.com/tylerl0706/alexa-spell](https://github.com/tylerl0706/alexa-spell)

* More info:
In the Alexa skill SSL cert page, I put in the URL generated by Claudia and also checked the " My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority" option.

**Comment by tylerl0706** [comment]
Hey there - Isabela and I working on this [online hackathon](https://alexakidskills.devpost.com/?ref_content=featured&ref_feature=challenge&ref_medium=discover) and the deadline is coming up so if you have any suggestions, we're all ears!

FWIW, I attempted to add "Alexa Skills Kit" to the lambda function hoping that would fix it (I, of course, updated the https url to the ARN) but instead, our skill now throws:

```
{ "errorMessage": "event does not contain routing information" }
```

Any thoughts? We are desperate and are depending on you guys 😢

**Comment by stojanovic** [comment]
Huh, you should be able to reuse most of the code by using this as a tmp solution: https://github.com/stojanovic/alexa-skill-kit/
It's a connection without API Gateway.

I don't think I can check the issue with this that fast.

**Comment by stojanovic** [comment]
Wait, are you using Claudia Bot Builder? If yes can you open an issue there, because this isn't Claudia issue?

**Comment by tylerl0706** [comment]
Done https://github.com/claudiajs/claudia-bot-builder/issues/110
