### ISSUE TITLE
Custom authorizer: add "Request Lambda Event Payload" feature

### ISSUE THREAD

**Issue by MEGApixel23** [claudiajs/claudia#144]
Is there a way to configure Request source instead of Token for Custom Authorizers?

Here is how we can select it from UI

<img width="458" alt="screenshot 2018-01-11 18 18 04" src="https://user-images.githubusercontent.com/4102786/34834902-f77421c8-f6fb-11e7-989d-0e34bff59854.png">

**Comment by gojko** [comment]
hi, please don't use github issues for questions, use the [gitter channel instead](gitter.im/claudiajs/claudia)
