### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by kendrickkesley** [claudiajs/claudia#145]
Hi, how do you use claudia js to tell API gateway to support multipart/form-data?
I'm using express JS and I'm currently manually set that mimetype in binary media section of API gateway.
without that support, the files uploaded to the lambda function will be corrupted.

How can I achieve that without manually adding the mimetype in the API gateway?

Thanks!

**Comment by gojko** [comment]
Hi - we use github issues for bugs only, questions and general discussion should go to the [claudia chat](https://gitter.im/claudiajs/claudia)
