### ISSUE TITLE
Trying to use 'generate' command gives "Generate template is missing"

### ISSUE THREAD

**Issue by jugglingcats** [claudiajs/claudia#155]
* Expected behaviour:
Files generated ready to deploy.

* What actually happens:
Error message as below.

* Steps to reproduce the problem:
```
node_modules/.bin/claudia generate --region eu-west-1 --hello-world
Generating...
Generate template is missing. If not familiar with the command, run claudia help.
```

Sorry if I'm missing something about this command but it doesn't seem to work.

**Comment by gojko** [comment]
i've removed the generate command from 5.x until we can do this properly
