### ISSUE TITLE
deploy is stack

### ISSUE THREAD

**Issue by roysG** [claudiajs/claudia#158]
Deploying is stack in..
"creating Lambda	lambda.setupRequestListeners"

**Comment by gojko** [comment]
if your lambda has lots of dependencies or the file is big for some other reason, use `--use-s3-bucket` to upload the zip first to an s3 bucket and then deploy from there. this will resolve your problem

**Comment by roysG** [comment]
Can i do upload and deploy in the same command?

**Comment by roysG** [comment]
I also tried this option and still is stack.
my project size is about 12.30mb (the node_modules is take all this space)

**Comment by roysG** [comment]
Works :)
