### ISSUE TITLE
Multiple lambda Entries in claudia.json

### ISSUE THREAD

**Issue by philltomlinson** [claudiajs/claudia#16]
I have a service that contains multiple lambdas. For example:

example-service
- lambda1.sj
- lambda2.js
- common.js

They both share common code hence why they are zipped up in the same service. Is there a way to specify multiple lambda entires within the claudia.json. A feature like this would be very useful to support multiple lambdas within the same folder.

{
  "lambda1": {
    "role": "role",
    "name": "lambda1",
    "region": "us-west-2"
  },
  "lambda2": {
    "role": "role",
    "name": "lambda2",
    "region": "us-west-2"
  }
}

**Comment by gojko** [comment]
I'm not sure I understand this, so please let me know if this comment is going in the wrong direction.

is this addressing a javascript package module problem?  if they just share common code, why would this be better than using the shared code as a NPM module and including it in two lambdas?

**Comment by philltomlinson** [comment]
So this is a case where I don't want to split both lambdas with their own package.json file, nor do I want to put the common code in another NPM module and include it as the code is fairly trivial.

So it may be a javascript package module problem, just wondered if it would be simple to support two lambdas within the same package.json? For example in package.json if it could be built to support two different endpoints:

```
"start1": "claudia create --name lambda1 --region us-west-2 --handler lambda1.handler",
"start2": "claudia create --name lambda2 --region us-west-2 --handler lambda2.handler",
"deploy": "claudia update"
```

Then in claudia.json you could also define two different lambdas entries and run the relevant deploy command and it would know about it. I realise this may be an edge case and not worth the extra complexity.

**Comment by gojko** [comment]
I think that would be easier to solve with multiple config files (eg if instead of `claudia.json` you could use separate config files for each of your lambdas). that would avoid some nasty edge cases caused by multiple lambdas configured in the same file. So you would use, for example, `claudia update --config lambda1.json`. Would that be an OK solution?

**Comment by philltomlinson** [comment]
That would be ideal, then you could just run the relevant --config option for the lambda you wished to update.

**Comment by gojko** [comment]
ok, that's relatively easy to do, i'll slot it into the next release

**Comment by gojko** [comment]
this is now possible, and on NPM as version 1.0.10; add `--config somethingelse.json` to the `create` command to save the config into an alternative file; add `--config somethingelse.json` to the `update` command to use the alternative config file. If you like, you can also rename existing `claudia.json` to something else and use it with `--config` for your updates

**Comment by gtennis** [comment]
So, is it possible to have single package.json and specify all the lambdas in one place? Like @philltomlinson mentioned? Yea, I noticed --config was added, but what about package.json and start1, start2, ...? And probably deploy1 (with config1), deploy2 (with config2), ...?

"start1": "claudia create --name lambda1 ...
"start2": "claudia create --name lambda2 ...
...
"startX": "claudia create --name lambdaX ...
"deploy": "claudia update"

**Comment by robfe** [comment]
@gojko If I wanted to write a couple of lambda functions that shared some common code that I didn't want to publish, is this the only way you'd recommend doing it? (i.e., one folder, one package.json, multiple claudia.json files)

Is something like `require('../shared/constants.js')` another option? would the file outside of the claudia project's root still be zipped up into both packages? (i.e. one folder per claudia project, each with it's own package.json, and then a `shared` folder next to those

**Comment by phips28** [comment]
We are using ../shared/ to import all the libs. 
In every package json we have a entry in "files" or in "dependencies".

**Comment by robfe** [comment]
@phips28 does that mean you need to pass `--use-local-dependencies` to claudia? If not what syntax do you use to specify the relative file in your package.json?

**Comment by gojko** [comment]
@robfe from claudia 1.9.0, released a few days ago, you can use normal NPM local references, even without --use-local-dependencies

**Comment by phips28** [comment]
@robfe this is our structure:
https://www.dropbox.com/s/qattkayqpfl4rcp/Screenshot%202016-09-23%2016.12.02.png?dl=0

we have to add this files into the `dependencies` because each of these folders have its own package.json with their own depencencies and `npm install` in the `api` folder will also install these node_modules inside the subfolder.
