### ISSUE TITLE
Allow specifying --deploy-proxy-api-type when creating a proxy api

### ISSUE THREAD

**Issue by ryan-mahoney** [claudiajs/claudia#165]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour:
`--deploy-proxy-api` should have an associated option such as `--deploy-proxy-api-type` to specify whether the API Gateway should be `regional` or `edge optimized`.

* What actually happens:
Currently, any generated proxy api defaults to being `edge optimized`. In the case of users who are putting their own CloudFront distribution in front of their API Endpoint, `edge optimized` endpoints result in duplicate Cloudfront network hops (and charges) as `edge optimized` uses a Cloudfront distribution under the hood.

* Link to a minimal, executable project that demonstrates the problem:
Any `claudia create` call that specifies `--deploy-proxy-api` will reproduce this issue.

* Steps to install the project:
n/a

* Steps to reproduce the problem:
n/a

**Comment by gojko** [comment]
would you like to submit a patch for this?

**Comment by ryan-mahoney** [comment]
I'll give it a try :)

**Comment by gojko** [comment]
great. the change is most likely going to be here:

https://github.com/claudiajs/claudia/blob/387e4dd3eb0bb70ee80bad1d00a79ce98749cd5b/src/commands/create.js#L201

You can use the local `options` variable to check command line options, I guess something like `--api-type` would work. Please also add a test to prove the new feature to [`create-spec.js`](https://github.com/claudiajs/claudia/blob/master/spec/create-spec.js), and information about the new parameter here, as the documentation is automatically built from it https://github.com/claudiajs/claudia/blob/387e4dd3eb0bb70ee80bad1d00a79ce98749cd5b/src/commands/create.js#L411

**Comment by gojko** [comment]
I'm closing this due to a week of inactivity. If anyone would like to pick up this later and submit a PR, please reopen it.

**Comment by ryan-mahoney** [comment]
@gojko I'll definitely pick this up eventually if no one else beats me to it. I need this functionality, but it's not super urgent at the moment. Sorry for delay!
