### ISSUE TITLE
Custom authorizer resultTtl default value is not valid

### ISSUE THREAD

**Issue by sartios** [claudiajs/claudia#166]
* Expected behavior:

Deploy a Lambda with a custom authorizer without setting a resultTtl value should disable the custom authorizer cache.

* What actually happens:

The TTL value of the custom authorizer is `undefined` which results in caching the policy document for the default value of 300 seconds.

In order to solve the issue, I have to define a resultTtl with 1 as a value at registerAuthorizer configuration.

```javascript
api.registerAuthorizer('customAuth', {
  lambdaName: 'customAuth',
  lambdaVersion: true,
  resultTtl: 1,
});
```

I have tried with zero as resultTtl value but results in set the value again as undefined.

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by gojko** [comment]
Can I just check if I understand this correctly? Are you saying that if the value is not provided, the AWS default gets applied, or does it not work at all?

**Comment by sartios** [comment]
If the value is not provided or is 0, at the AWS is set as undefined, which results in caching the policy for 300 seconds

**Comment by gojko** [comment]
I'm closing this due to a week of inactivity -- if anyone wants to pick this change up later and submit a pull request, please reopen it.
