### ISSUE TITLE
Command Line Argument to Deploy files even though they're matched by .gitignore?

### ISSUE THREAD

**Issue by LukeMizuhashi** [claudiajs/claudia#168]
Claudia is amazing! Absolutely love it. Nonetheless, a small issue I'm having: I'm using Claudia to build an API that generates JSON Web Tokens. As such, I need the lambda function that generates JWTs to have access to my private key.

Until I figure out something smarter, I'd like the private key to exist as a file alongside the JavaScript that implements the function in AWS Lambda.

I'd also like to put the name of my private key in .gitignore--so that it doesn't get published to the Interwebs.

But, I see that adding a file to .gitignore also causes Claudia to not deploy the file.

Is there a better practice than what I'm doing here? Is there a way to tell Claudia to deploy a file even though it's filtered out of the Git record by .gitignore?

Thanks, everyone! Love this project.

**Comment by gojko** [comment]
Hi, please use github issues only for bugs, this is a question and should go to the gitter chat channel (https://gitter.im/claudiajs/claudia). that helps us keep github issues clean. thanks!
