### ISSUE TITLE
claudia create/update should work well with patch-package

### ISSUE THREAD

**Issue by ceefour** [claudiajs/claudia#170]
[patch-package](https://www.npmjs.com/package/patch-package) is very useful for forking/fixing a problem in the meantime before official bugfix.

---

* Expected behaviour: deployed code runs patch-package (i.e. `prepare` script in `package.json`)

* What actually happens: claudia npm installs the "pure packages" without running patches, this can be verified by using `claudia --keep`

* Link to a minimal, executable project that demonstrates the problem: any project with any patch-package patch

* Steps to install the project: `claudia create` / `claudia update`

* Steps to reproduce the problem: 

1. `npm install --save patch-package`
2. edit a file e.g. `node_modules/aws-serverless-express/express/src/index.js`  even adding comment will do
3. `npx patch-package aws-serverless-express`
4. `claudia create --keep ...`

**Comment by ceefour** [comment]
Workaround from @stojanovic : 

> you can use `--use-local-dependencies` option in Claudia and deploy whatever you have in your local `node_modules`, or simply fork a repo and fix the issue, just install the module from your fork, not from NPM.

**Comment by gojko** [comment]
@ceefour one of the goals of Claudia is not to introduce too much magic, so we use NPM for package management. local dependencies are the right way to solve it, not a workaround, so I’ll close this issue.
