### ISSUE TITLE
Proxy APIs and IAM authentication

### ISSUE THREAD

**Issue by csepulv** [claudiajs/claudia#171]
I'd like to use a proxy API as described in https://claudiajs.com/tutorials/deploying-proxy-api.html.

However, I don't see a way to require IAM authentication, as I would with an API router method, like `authorizationType: 'AWS_IAM'`.  (https://github.com/claudiajs/claudia-api-builder/blob/master/docs/authorization.md)

Is there a way to do this with the `--deploy-proxy-api`? I can manually update on AWS, but I prefer to use Claudia to manage the deployment/config.

**Comment by gojko** [comment]
please use the chat channel for questions (https://gitter.im/claudiajs/claudia), we keep github issues for bugs only
