### ISSUE TITLE
deploy into an existing lambda function

### ISSUE THREAD

**Issue by cosminonea** [claudiajs/claudia#177]
this is not an issue, just a question

I am creating all the infrastructure using terraform, and that includes the AWS lambda functions and api gateway configs.

Is there any way to deploy into an existing function using claudia? 
The same way we can specify a role ARN, is there a way/workaround to specify the function name?

**Comment by gojko** [comment]
please use the gitter channel for questions <https://gitter.im/claudiajs/claudia>
