### ISSUE TITLE
Add support or instructions for new WebSocket lambdas build and deploy use-cases

### ISSUE THREAD

**Issue by JustFly1984** [claudiajs/claudia#178]
There is a new feature 

https://docs.aws.amazon.com/en_us/apigateway/latest/developerguide/apigateway-websocket-api.html

I would love to ditch our current qraphql setup, and move back (again! ) to realtime networking.

Thank you for a great tool!

**Comment by gojko** [comment]
Hi - we use github issues only for bugs. please use the [gitter chat channel](https://gitter.im/claudiajs/claudia) for discussions
