### ISSUE TITLE
claudia bot builder- facebook v3.2 integration issue

### ISSUE THREAD

**Issue by AmrZoheir** [claudiajs/claudia#179]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

*** Expected behaviour:**
After running claudia update --configure-fb-bot, the bot should exit successfully (indicating succesful bot setup)
*** What actually happens:**
However, on newly created App (using newly created Page), it seems that this App is mandatorily using v.3.2 Graph API, and it exit with following error:

{"error":{"message":"(#100) The parameter subscribed_fields is required.","type":"OAuthException","code":100,"fbtrace_id":"xxxxxxx"}}
* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by gojko** [comment]
this is related to claudia bot builder, not claudia, so I'll close the issue here to keep things clean
