### ISSUE TITLE
TooManyRequestsException (setting up lots of API gateway endpoints)

### ISSUE THREAD

**Issue by hgoldwire** [claudiajs/claudia#18]
HI gang, first up thanks for making claudiajs because I freaking love it.  I love it so much I've made a web api with 13 endpoints, and counting.  When I add a 14th endpoint, "claudia update" gives me this error, which I imagine comes from making lots of API Gateway calls during update.  Anyone else run into this?

{ [TooManyRequestsException: Too Many Requests]
  cause:
   { [TooManyRequestsException: Too Many Requests]
     message: 'Too Many Requests',
     code: 'TooManyRequestsException',
     time: Wed Mar 02 2016 15:31:50 GMT-0500 (EST),
     requestId: 'caa4ac2b-e0b5-11e5-a1ee-672085005625',
     statusCode: 429,
     retryable: false,
     retryDelay: 34.01342041324824 },
  isOperational: true,
  code: 'TooManyRequestsException',
  time: Wed Mar 02 2016 15:31:50 GMT-0500 (EST),
  requestId: 'caa4ac2b-e0b5-11e5-a1ee-672085005625',
  statusCode: 429,
  retryable: false,
  retryDelay: 34.01342041324824 }

**Comment by gojko** [comment]
I guess this is some throttling coming from AWS. According to the SDK, it should retry automatically, but it seems that it started rejecting it for you instead of retrying. I can implement some kind of retry on the client end.

**Comment by gojko** [comment]
I've just created and re-created an API with 40 endpoints, trying to reproduce your problem, so either I'm doing something horribly different or the error is somewhere else. 

What AWS region are you using?

if the API file you're using isn't horribly secret, would you mind sharing it with me so I can try to work with the exact same definition? Perhaps there's something data-specific that you're hitting and I'm not.

**Comment by hgoldwire** [comment]
I'm using us-east-1, but actually now I can't recreate it either.  Maybe close this issue and if I have problems again I'll forward a repeatable test case?  Apologies for the diversion. - Henry

**Comment by gojko** [comment]
no problem, if it reappears let me know. I can only assume you were caught in some temporary bug that got the TooManyRequestsException to not be retryable, and they fixed it meanwhile

**Comment by adrai** [comment]
now I have this too:

```
{ [TooManyRequestsException: Too Many Requests]
  cause:
   { [TooManyRequestsException: Too Many Requests]
     message: 'Too Many Requests',
     code: 'TooManyRequestsException',
     time: Fri Mar 25 2016 12:52:40 GMT+0100 (CET),
     requestId: '147007bf-f280-11e5-bc86-e7177b0024cb',
     statusCode: 429,
     retryable: false,
     retryDelay: 70.80414441879839 },
  isOperational: true,
  code: 'TooManyRequestsException',
  time: Fri Mar 25 2016 12:52:40 GMT+0100 (CET),
  requestId: '147007bf-f280-11e5-bc86-e7177b0024cb',
  statusCode: 429,
  retryable: false,
  retryDelay: 70.80414441879839 }
```

**Comment by gojko** [comment]
I'm investigating this now. it looks as if something changed on the AWS side to no longer accept some requests in parallel, but the error isn't saying which request actually failed.

**Comment by gojko** [comment]
it seems that toomanyrequestsexception is now sent back as non-retriable, which I can only assume is a bug in AWS SDK. This is why the SDK client is not trying again automatically. 

This seems to be a recurring bug, so I'm adding a wrapper around API Gateway calls now that will retry automatically when this happens.

**Comment by gojko** [comment]
I've pushed version 1.0.19 to NPM, with automatic retrying for TooManyRequestsException

**Comment by adrai** [comment]
thx
