### ISSUE TITLE
Support for node 10 LTS lambdas deploy

### ISSUE THREAD

**Issue by JustFly1984** [claudiajs/claudia#188]
I have read this article: https://aws.amazon.com/blogs/developer/node-js-6-is-approaching-end-of-life-upgrade-your-aws-lambda-functions-to-the-node-js-10-lts/

Is it possible to use claudia with node.js 10?

**Comment by gojko** [comment]
hi - please don't use github issues for questions, use <https://gitter.im/claudiajs/claudia> instead

**Comment by JustFly1984** [comment]
Thank you, I have made a post in gitter
