### ISSUE TITLE
ES2015 support?

### ISSUE THREAD

**Issue by aidanbon** [claudiajs/claudia#19]
First, thanks for this awesome _frictionless_ serverless framework. It really lower the barrier for Node.js into Lambda.

Is supporting ES6 (e.g. via Babel transpilation) in the roadmap?

**Comment by gojko** [comment]
what kind of support would you need there? 

NPM should already do everything for you. You can use babel as a dependency and perform transpilation in the `postinstall` npm script, the resulting JS will be uploaded to Lambda.

Is there anything more you expect Claudia to provide?

**Comment by lindekaer** [comment]
@gojko `postinstall` is sufficient 🚀

Could you provide an example for a setup?
I currently have:

```
├── node_modules
├── handler.js
└── package.json
```

with 

`"postinstall": "babel handler.js --out-file handler.js"` in `package.json`

I would like to have a `handler-src.js` and `handler-build.js` and deploy the **build** version when deploying with Claudia. Can I instruct Claudia to use a handler that has not yet been created when running `claudia create`?

**Comment by gojko** [comment]
@lindekaer please use the gitter chat channel for general discussion. https://gitter.im/claudiajs/claudia

**Comment by phips28** [comment]
@lindekaer we use a build folder and webpack, minify it before deploy. More on gitter

**Comment by aidanbon** [comment]
I use Babel in npm script - Example: https://github.com/claudiajs/example-projects/tree/master/graphql-example

**Comment by SgtPooki** [comment]
postinstall doesn't seem to be ran with the latest version of claudia
```
claudia --version
2.14.2
```

**Comment by gojko** [comment]
claudia just uses `npm install --production`, so something in your NPM config is likely the cause. does postinstall run when you just do npm install locally without claudia?
