### ISSUE TITLE
Claudia package validation fails with Lambda Layers

### ISSUE THREAD

**Issue by jlarmstrongiv** [claudiajs/claudia#194]
* Expected behaviour:
Claudia packages and publishes my lambda function.

* What actually happens:
It errors out during package validation, saying 
```
validating package
Error: Cannot find module 'sharp'
  at…
```
Sharp is a module I put into Lambda Layers.

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

I understand why claudia is throwing errors.  I do not actually have that module installed.  It is actually installed inside the Lambda Layer, which the package validator has no knowledge of.  

It would be great to either pass an array of packages included in lambda layer to ignore validation errors for those packages.  Or, as a quickfix, just skip the validator when using Layers.  There’s probably other solutions I am unaware of.  

Adding sharp as a dev or optional dependency did not work.

**Comment by gojko** [comment]
A workaround is to lazy-load sharp - don't require it in the main instantiation chain for the entry-level class. So require and load it inside a function that actually uses it.

Claudia needs to instantiate the API class to read the configuration, so the current design makes it impossible to skip validation.

**Comment by jlarmstrongiv** [comment]
This package solved my problems [https://github.com/sindresorhus/import-lazy#usage-with-bundlers](https://github.com/sindresorhus/import-lazy#usage-with-bundlers)

**Comment by nick-tw** [comment]
thanks. lazy load works for sharp.
