### ISSUE TITLE
--npm-options=--ignore-scripts ignores --post-package-script

### ISSUE THREAD

**Issue by SMGitAdmin** [claudiajs/claudia#195]
I have a package.json with a "postinstall" that I do not want to execute when packaging for lambda, but has a script that I do want claudia to use for --post-package-script.  Something like this:

```js
{
  ...
  "scripts": {
    "postinstall": "(cd unused; npm install)",
    "claudia-post-package": "dosomething.sh"
  }
  ...
```

```sh
$ NODE_ENV=dev npx claudia pack --post-package-script claudia-post-package --output ~/tmp/claud.zip --force --npm-options=--ignore-scripts
```

That command does ignore the "postinstall" script, but it seems the "claudia-post-package" script was ignored as well.  I can understand the argument that "you asked claudia to ignore scripts!", but I also explicitly asked claudia to post-package.

**Comment by gojko** [comment]
I don't think this is something we can fix with the current NPM invocation system, but I'll keep it in mind if we redesign that part. npm options are passed to all npm invocations, using the post-package script, without trying to contextually understand what they are.
