### ISSUE TITLE
Allow custom CORS origins

### ISSUE THREAD

**Issue by ilikebits** [claudiajs/claudia#2]
I currently use a custom lambda function which handles `OPTIONS` requests so I can allow or disallow arbitrary domains for CORS. Is there a way I can do this with Claudia?

**Comment by gojko** [comment]
At the moment, CORS origins are hard-coded to `*` (all origins allowed). It should be easy to add some more flexibility there, eg allow people to specify an options handler or provide a list of domains supported. 

What does your current function use to decide if the request should be allowed or not?

**Comment by ilikebits** [comment]
Right now I'm using it as an API that I only want my own domains to be able to call, so it echoes the domain name if the caller's domain is mine and doesn't return any origin header otherwise (see [SO](http://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains)). I can imagine a case where I'd want to be able to dynamically allow others to use my API and so I'd write a lambda function that pulls a list of allowed origins from e.g. DynamoDB.

**Comment by gojko** [comment]
and is this restriction global for all your API calls, or is it on individual paths? is the way forward to specify an OPTIONS handler globally for the entire API, or do you need finer grained control where different options apply to different request paths?

**Comment by ilikebits** [comment]
I specify one globally for my whole API because I don't have a need for CORS control at the endpoint granularity, but I'd love to hear others' thoughts on this.

**Comment by gojko** [comment]
this is now supported, with API Builder 1.1.0 and Claudia 1.1.0; see https://github.com/claudiajs/claudia-api-builder#controlling-cross-origin-resource-sharing-headers for more information
