### ISSUE TITLE
Cannot use --api-module with --deploy-proxy-api

### ISSUE THREAD

**Issue by Rulasmur** [claudiajs/claudia#202]
* Expected behaviour:
Should be able to use api-module along with deploy-proxy-api

* What actually happens:
```
> claudia create --region eu-west-1 --api-module index --deploy-proxy-api --handler index
incompatible arguments: cannot specify handler and api-module at the same time.
> claudia create --region eu-west-1 --api-module index --deploy-proxy-api
deploy-proxy-api requires a handler. please specify with --handler
```

* Steps to reproduce the problem:
```
claudia create --region eu-west-1 --api-module index --deploy-proxy-api
```

**Comment by gojko** [comment]
those two options are mutually exclusive, so the error is correct. if you want to use claudia api builder, use `--api-module`; if you want to just deploy a proxy api and not have claudia set up routes for the api builder, use --deploy-proxy-api
