### ISSUE TITLE
question about post-package-script

### ISSUE THREAD

**Issue by ispyinternet** [claudiajs/claudia#204]
If you have quite an extensive `devDependencies` list, writing a script to `npm uninstall` them all afterwards could become quite tedious.

Could we not keep the `devDependencies` until after the post-package-script has completed, and then under the hood claudia could run `npm prune --production`?

**Comment by ispyinternet** [comment]
I guess there is nothing to stop you building the bundle before you `claudia pack` anyhow?

**Comment by gojko** [comment]
Hi - please send questions to the gitter chat channel, we use github issues only for bugs https://gitter.im/claudiajs/claudia
