### ISSUE TITLE
Claudia pack --no-zip option?

### ISSUE THREAD

**Issue by ispyinternet** [claudiajs/claudia#205]
Is this a reasonable request?

I suppose looking at my use case, I am relying on claudia pack to take the headache out of sym links so I can use `sam local start-api`.

Having to unpack the zip each request is tedious. If claudia pack could place the unzipped files in a specified folder? Or should one be expected to perform this manually afterwards??

**Comment by gojko** [comment]
Hi - please send questions to the gitter chat channel, we use github issues only for bugs. https://gitter.im/claudiajs/claudia
