### ISSUE TITLE
Specify path on S3 used for upload

### ISSUE THREAD

**Issue by apeeters** [claudiajs/claudia#208]
It would be nice to have an option to specify the path on the S3 bucket to be used for storing the packaged Lambda code.

Proposal: `--s3-path`

* Expected behaviour:

Use path with `--use-s3-bucket`

* What actually happens:

The packaged zip is stored in the root of the s3 bucket.

**Comment by gojko** [comment]
Hi - we use github issues only for bugs. please use the gitter chat channel (https://gitter.im/claudiajs/claudia) to propose and discuss features
