### ISSUE TITLE
WTF Claudia did to my project?

### ISSUE THREAD

**Issue by CovertCode** [claudiajs/claudia#213]
I completed my microservice and used claudia. Now after 15 days I thought to add just one variable to retrive data from a submitted form. As usual I updated my app with **claudia update** but the change wasn't reflected. I did it 2 times and then I noticed my URL to that function got changed after the updated. I was thinking I did something wrong in between. But no it was claudiajs crap which changed the URL and ripped my mind.
Can you tell me why this happened?

**Comment by gojko** [comment]
Hi - we use github issues only for bugs. for questions and general discussion, please use the gitter chat channel: https://gitter.im/claudiajs/claudia
