### ISSUE TITLE
Can I specify Lambda function name to be different than the API name?

### ISSUE THREAD

**Issue by julipur** [claudiajs/claudia#23]
we have a naming convention for our lambda's so would like to have a different name for the lambda and the api. Is that currently possible?

**Comment by gojko** [comment]
not at the moment, but you can add another option to `--create` if you want. You'll need to change line 79 of [create.js](https://github.com/claudiajs/claudia/blob/master/src/commands/create.js#L79). Please also add a [test for that](https://github.com/claudiajs/claudia/blob/master/spec/create-spec.js), and update the [usage guide](https://github.com/claudiajs/claudia/blob/master/bin/usage.txt) with the new option, and i'll merge the pull request. It would be good if the new parameter doesn't easily get confused with `api-module`, so making clear that it's a name would be best. Something like `api-name`, I guess.

**Comment by gojko** [comment]
this is now on NPM, as 1.0.13; using a single file for all three content types. the relevant commit change is https://github.com/claudiajs/claudia/commit/9cb579e255f7bdd812791fe8c01da70f5116b808

**Comment by julipur** [comment]
Thanks @gojko. Based on the usage guide, it seems like --config is to replace the claudia.json file?

**Comment by gojko** [comment]
no, --config points to an alternative file. so you can launch multiple lambdas from the same folder/NPM project source
