### ISSUE TITLE
ValidationException: 'sourceArn' failed to satisfy constraint

### ISSUE THREAD

**Issue by lukehoban** [claudiajs/claudia#3]
When I run the tests, I see a large number of failures (47/122), almost all of which are due to:

```
Failed: 1 validation error detected: Value 'arn:aws:execute-api:us-east-1:AIDAI2YYF3TYCI65FI3IM:rfj3hl9en0/*/*/*' at 'sourceArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:([a-zA-Z0-9\-])+:([a-z]{2}-[a-z]+-\d{1})?:(\d{12})?:(.*)
```

Indeed - the code appears to be using the Access Key ID (`GetUser().User.UserId`) instead of the Account ID in forming the `sourceARN`.

I see similar failures for any of the `example-projects` other than `hello-world`.

Is there some more specific requirement on how AWS credentials are provided to Claudia for these tests/examples to work?

**Comment by gojko** [comment]
are you using your root account, or an IAM user to try things out? I assume that might be the problem. 

I expected the UserId to return a numeric IAM User ID, but in your case it seems to return the key identifier, not the user identifier. Obviously, wrong assumption, so I'd like to try to make this work for a wider case, which means I'll need to get the numeric ID from somewhere else.

What is the ARN that you get when you execute GetUser in the console? Does that contain a numeric ID or the access key ID again?

**Comment by lukehoban** [comment]
My credentials are using an access key for an IAM user.  

```
$ aws iam get-user
{
    "User": {
        "UserName": "adminuser",
        "Path": "/",
        "CreateDate": "2016-02-15T01:16:45Z",
        "UserId": "AIDAI2YYF3TYCI65FI3IM",
        "Arn": "arn:aws:iam::490047557317:user/adminuser"
    }
}
```

You can parse the account id out of `User.Arn` perhaps?

**Comment by gojko** [comment]
ok, I'll parse it from the ARN, that seems to be more reliable.

**Comment by gojko** [comment]
I've pushed version 1.0.1 to NPM with a potential fix for this. Can you please try it out? I've updated the example projects also to use the latest version, so you can either run the tests in this project or update/try to use the web api example project

**Comment by lukehoban** [comment]
Great.  Tests are examples are all working for me now.

**Comment by gojko** [comment]
great. thanks for reporting this!
