### ISSUE TITLE
Please allow user editable json templates for apigw-params.txt

### ISSUE THREAD

**Issue by cevatkerim** [claudiajs/claudia#31]
In order to make use of custom authenticators, one needs access to custom $context variables for things like user id. It would be great if a custom template could be provided to claudia.

**Comment by gojko** [comment]
a custom file would potentially break the parameter parsing. if you're only looking for a few more fields in the context, just add them to the main file and submit a pull request. please also add a test to make sure that the right conversion happens.

**Comment by cevatkerim** [comment]
It really depends on what you need passed onto lambda from custom authenticator. I might need a single uid field whereas someone else might need something different.

**Comment by gojko** [comment]
add the stuff you need, when the 'someone else' finally appears, they'll do the same

**Comment by gojko** [comment]
claudia api builder now exposes all the identity fields from the context variable: https://github.com/claudiajs/claudia-api-builder#the-request-object
