### ISSUE TITLE
Lambda now supports node 4.3

### ISSUE THREAD

**Issue by tanepiper** [claudiajs/claudia#32]
As per https://aws.amazon.com/about-aws/whats-new/2016/04/aws-lambda-supports-node-js-4-3

Will Claudia support this out the box in the current version, or does it need to add support?

**Comment by gojko** [comment]
from what I understand (need to investigate further), a very small change needs to happen so that Claudia requests the new runtime. I will do this tonight

**Comment by gojko** [comment]
Claudia 1.2.0 is now on NPM, and creates 4.3 deployments automatically. You can force an older deployment using `--runtime nodejs` when creating the function. 

https://github.com/claudiajs/claudia/commit/ee9ba3fb58765e6d127ac3def9bf2afed37001e0

**Comment by tanepiper** [comment]
@gojko Do you know if this will automatically upgrade existing deployments? Or do we need to re-create a new app?

**Comment by gojko** [comment]
it won't upgrade automatically. I don't know of a way to upgrade this, as the documentation for 
`aws lambda update-function-configuration` doesn't mention the runtime argument. It may be safest to just create a new deployment after you've tested that the code works well in 4.3.2
