### ISSUE TITLE
Best practices for handling production vs development variables

### ISSUE THREAD

**Issue by jcn** [claudiajs/claudia#33]
I know that claudia can handle the deployment of different versions of code, but what is the best practice for deploying a production or a development version of the app that needs to, say, connect to a different backend service depending on which environment it is running in? A typical 12factor solution might be to use environment variables, but this really isn't supported in Lambda. How would you recommend approaching this?

EDIT: I know that API Gateway has stage variables, but it doesn't seem like Lambda has the same thing. https://github.com/claudiajs/claudia-api-builder/issues/9

**Comment by gojko** [comment]
not sure if this is 'best practice', but my current practice is:
1. if the event can contain an origin, no config needed. eg S3 event for file uploads contains the S3 bucket. our exporters are configured so that a bucket triggers an event for `:production` or `:development`, so the event comes to the right version, and the lambda just uses the bucket from the event to read and convert the file.
2. if that's not enough, upload config files named after versions (eg `production.json`) and then use `context.functionVersion` to select which config to load during processing

**Comment by jcn** [comment]
In our particular use case, our events are triggered by an SNS notification and in development they are going to be making API calls either into a live environment (production) or a sandboxed one (development), so we can't really pass in something like an S3 bucket.

For `context.functionVersion` I'm not sure how this would work in practice. The docs say: "If an alias is used to invoke the function, then function_version will be the version the alias points to." Doesn't this mean that `context.functionVersion` would be something like `8` instead of `production`?

**Comment by gojko** [comment]
alias is "production", if you invoke it with `:production`. if you invoke it with `:8`, then it will be "8", but I prefer to use named aliases when invoking, so I don't have to reconfigure source events. you can set a named alias using `--version` for `create`, `update` and `set-version` using claudia.

**Comment by jcn** [comment]
Oh, ok, this seems inconsistent with the docs, but I'll test it out and see what happens. Thanks.

**Comment by gojko** [comment]
sorry, just read that more carefully, you are right. the stuff you can use is the `invokedFunctionArn`

**Comment by gojko** [comment]
Here's an example showing how you can detect the alias: https://github.com/claudiajs/example-projects/tree/master/detecting-context

**Comment by jcn** [comment]
Great, thanks. Hopefully Lambda will support environment variables at some point.

**Comment by hackerunet** [comment]
is 2019,. and not sure if this is still the case, but I'm a bit lost how can I use dotenv instead of .json files as claudia docs says. Any thoughts?
