### ISSUE TITLE
Specify MemorySize of the Lambda

### ISSUE THREAD

**Issue by EricPKerr** [claudiajs/claudia#36]
Claudia should expose the ability to specify the memory size of the Lambda instance to override the default 128MB.  This would allow users to customize the project for more endpoints that experience higher API traffic with an optional lambda.memory integer in the claudia.json configuration.

**Comment by gojko** [comment]
This is a nice, useful, and simple change, ideal for someone new to try submitting code. the key change is to https://github.com/claudiajs/claudia/blob/master/src/commands/create.js#L75 (check out http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property for docs) and a test would pretty much look like the one in https://github.com/claudiajs/claudia/blob/master/spec/create-spec.js#L318

Any takers?

**Comment by aidanbon** [comment]
Hey, I can give it a try. I have some exposure to create.js from my last PR to add a description field to the Claudia Lambda function. However, due to crazy schedule at my day job, I can't guarantee a timeline, but  will spend sometime this weekend. If there are other sooner takers, feel free.

**Comment by aidanbon** [comment]
Okay, in addition to the memory size configuration, I also added the timeout support.
See https://github.com/claudiajs/claudia/pull/37.

**Comment by gojko** [comment]
this is now on NPM as 1.2.6. Thanks @aidanbon

**Comment by ceefour** [comment]
Is this the correct way in `claudia.json` ?

```
  ...,
  "timeout": 6,
  "memory: 512
```

Because there is no documentation on `claudia.json` format, only `claudia create`. Problem is, we usually need to change memory/timeout during development, not by recreating the app.

**Comment by gojko** [comment]
@ceefour please use the [gitter chat channel](https://gitter.im/claudiajs/claudia) for questions
