### ISSUE TITLE
Using dotenv with Claudia

### ISSUE THREAD

**Issue by duboff** [claudiajs/claudia#39]
Hi, previously I was able to use dotenv with Claudia by adding my `.env` file to the `files` property of the package.json. However, now it is ignored. I imagine this is because the file is in .gitignore. Can you please clarify if this is a desired behaviour?

I would think `files` property should dominate over .gitignore

**Comment by gojko** [comment]
files should override .gitignore, i'll check. is your .env explicitly included in the files section?

**Comment by gojko** [comment]
this is fixed in 1.2.7, now on NPM. if the files property is specified in package.json, Claudia now just ignores .gitignore/.npmignore. Please let me know if this solved your problem

**Comment by duboff** [comment]
Confirm, everything works as expected. Thank you!

**Comment by jmike** [comment]
Shouldn't the same apply to folders? Currently the "files" property has precedence over .gitignore / .npmignore for individual files, but not folders.

**Comment by gojko** [comment]
@jmike since 2.2.0 claudia just uses `npm pack` to produce the package, so check the NPM `package.json` docs if you need to exclude/include folders. you can test if it gets created correctly by just running `npm pack` directly
