### ISSUE TITLE
Testing locally

### ISSUE THREAD

**Issue by dennisvdvliet** [claudiajs/claudia#4]
Any ideas on testing the simple API examples locally?

**Comment by gojko** [comment]
it's quite easy. I still need to write up the docs about that, but here's the gist:

0. [Initialise AWS credentials](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) if you're using any additional services, so your unit tests can connect to other services.
1. require your api module
2. inside the test, execute `api.router(requestObject, lambdaContextSpy)`

the `requestObject` is whatever you want the function to process, as [explained here](https://github.com/claudiajs/claudia-api-builder#the-request-object), with the constraint that you have to include `context.path` and `context.method`. Here's an example:
```
apiRequest = {
	context: {
		path: '/echo',
		method: 'GET'
	},
	queryString: {
		name: 'mike'
	}
};
````

the `lambdaContextSpy` should have one method, `done`, that's the expected Lambda callback. That's a classic callback method (two arguments, first is the error, second is the successful result). For info on the context, check out the [Node.js programming model](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html)

**Comment by gojko** [comment]
I have finally published a tutorial with examples, check out https://claudiajs.com/tutorials/testing-locally.html
