### ISSUE TITLE
Cannot find module if create with source and api-module parameters

### ISSUE THREAD

**Issue by flyingsky** [claudiajs/claudia#40]
I use command `claudia create --region us-east-1 --api-module lambda.js --source ./build/src`, it throws error cannot find module `build/src/lambda`. The reason is create command use require(path.join(source, apiModule)) to find module, which will discard '.'.

**Comment by aidanbon** [comment]
Pay attention to the error stack message. If you see:
>  Error: Cannot find module 'claudia-api-builder'

It means you missed running _npm i_ at your project folder before launching the _claudia_ command.

**Comment by gojko** [comment]
I'm not sure I 100% understand the situation, so let me know if this fixes it or not... `api-module` is not a path to a JS file, it's the name of a module that is configured for your Lambda function. So if there is a file called `index.js` in your `build/src/lambda`, the `api-module` parameter should just be `index`.

If this doesn't fix it, can you post the entire error?

The `require` command is there to prevent sending broken code to Lambda, it tests if the configuration will actually result in something that Lambda can load or not. So it's correct, and prevented you from sending something that wouldn't work when deployed.

**Comment by gojko** [comment]
I found a potential problem with relative `--source` paths and that's now fixed (Claudia 1.2.8 is on NPM). This will still require you to use a module name, not a file path for `api-module`, but it should work with relative paths. please reopen the issue if it does not fix it.

**Comment by flyingsky** [comment]
fixed. thanks.

**Comment by daronjones** [comment]
You may also get this error if you've put dependencies in the `dev-dependencies` with `--save-dev`.

I'm guessing that we should use the `--no-optional-dependencies` to get around this.
