### ISSUE TITLE
TypeError: Cannot redefine property: $map

### ISSUE THREAD

**Issue by tanepiper** [claudiajs/claudia#42]
I've been asked to do some fixes on a project I developed with Claudia.  I've tried to deploy them and I get the above error:

```
> claudia update
> updating REST API
> [TypeError: Cannot redefine property: $map]
```

I've had a look in the source (both Claudia and my own app) and can't find anything that this might reference.  I've tried to go back to 1.2.0, the last version I used to deploy successfully with no luck.

Locally I'm using node v4.4.1, although remove version is using node 4.3 (but I would not expect any major compatibility).

As an aside, one thing that might be useful is when there is an error to do the following:

`console.log(error.stack)`

As the stack is being swallowed up and only the error.message is being shown.

**Comment by gojko** [comment]
can you narrow it down to a REST API definition (eg api.get('....')) that causes problems, so I can investigate? Or share your API definition file?

**Comment by tanepiper** [comment]
@gojko Here you go: https://gist.github.com/tanepiper/2067ccb227c3b9912fe7264788e1ab1a

`claudia-api-builder` is `1.1.0`

**Comment by tanepiper** [comment]
@gojko Been unable to narrow it down, like I said in OP the stack trace is being swallowed up (a common issue I see with promises)

Another useful thing I've found recently is this:

```
process.on('unhandledRejection', function (err) {
  /*eslint-disable */
  console.log(err.stack);
  process.exit(1);
  /*eslint-enable */
});

process.on('uncaughtException', function (exception) {
  /*eslint-disable */
  console.log(exception); // to see your exception details in the console
  process.exit(1);
  /*eslint-enable */
});
```

It ensures that the stack gets dumped when there is an unhandledRejection

**Comment by tanepiper** [comment]
@gojko Hey! So despite this errors it looks like the app is being updated after all!

I had another bug that masked the issue.  Anyway I tested with deploying a new app, same error.  But I noticed the existing app had updated it's latest after all.

So it looks like some kind of post-deploy message is failing.

**Comment by gojko** [comment]
@tanepiper I found the bug. One of the dependencies you used was non-reentrant (pg-promise), and claudia tried to load it twice, causing the error. I've fixed that, so claudia can now work with non-reentrant modules, and you should be able to use version 1.3.1 (now on NPM) to update your deployment. In addition, errors such as that one should now be logged with a stack trace, so troubleshooting similar things in the future should hopefully be easier.

please let me know if this fixes your problem

**Comment by vitaly-t** [comment]
I will be updating `pg-promise` to stop using `$map` and methods like that. Will provide an update when finished.

**Comment by tanepiper** [comment]
@gojko @vitaly-t Open source :star2:'s

**Comment by vitaly-t** [comment]
I have fixed this issue in `pg-promise` and released [v.4.3.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.3.1).
