### ISSUE TITLE
can we use private modules with claudia deployment?

### ISSUE THREAD

**Issue by victusfate** [claudiajs/claudia#43]
```
"dependencies": {
  "myPrivateModule: "git+https://oauthToken:x-oauth-basic@github.com/user/myPrivateModule.git"
}
```

**Comment by gojko** [comment]
you should be able to, no issues expected there, just make sure `npm install --production` works well on the machine where you will deploy from (that is what claudia executes after copying files to a temp folder to create the package). You probably don't even need to specify the auth tokens as long as the currently logged in user has access to the git repo

**Comment by victusfate** [comment]
thanks @gojko, I'll test next week
