### ISSUE TITLE
How to determine under which account the lambda function was created

### ISSUE THREAD

**Issue by nordhagen** [claudiajs/claudia#45]
I operate several AWS accounts. In my ~/.aws/credentials file I only have one entry, which are credentials that are only valid for one of them. When I first ran the claudia create command, the endpoint was  created under a different account than the one the credentials are valid for. When i ran the command for a different project with the credentials unchanged everything seems fine, but the lambda function is not created under the same account. Actually I cannot find the lambda function that Claudia claims to have created under any of my accounts.

**Comment by gojko** [comment]
Claudia doesn't track that, but you can use AWS command line for that

```bash
aws lambda list-functions --query 'Functions[].FunctionName' --output text --profile <PROFILE>
```
