### ISSUE TITLE
Error responses from API Builder are always stringified

### ISSUE THREAD

**Issue by thadd** [claudiajs/claudia#46]
I'm trying to send back detailed error responses as JSON from an API Builder method but it won't return JSON representation of my result. Here's a sample API project that demonstrates the problem:

```javascript
"use strict";

var ApiBuilder = require("claudia-api-builder");
var AWS = require("aws-sdk");

var api = new ApiBuilder();
module.exports = api;

api.post("/dummy", function (request) {
  if (request.body.foo === "bar") {
    return {status: "OK"};
  } else {
    throw {error: "Invalid request"};
  }
});
```

If you then call that API like this: 

```
POST /latest/dummy
Request Headers & Body
Accept: */*
Accept-Encoding: gzip, deflate
Content-Type: application/json
Accept-Language: en-us

{
  "foo": "baz"
}
```

You get the following response:

```
Response Headers
HTTP/1.1 500 Internal Server Error

Connection: keep-alive
Content-Type: application/json
X-Cache: Error from cloudfront
x-amzn-RequestId: 04957e7b-28d5-11e6-b1c5-991fd1d7258a
Via: 1.1 dc7c4fb5024ff022cad1642ec506a6e8.cloudfront.net (CloudFront)
Date: Thu, 02 Jun 2016 15:16:45 GMT
Access-Control-Allow-Headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key
Content-Length: 34
X-Amz-Cf-Id: 1Y4Tb4lS7W6zDBoJkqOetlnPkKByi-R5WXeHC8fwxkbZKWGtTIGqXw==
Access-Control-Allow-Origin: *

Response Body Display Options 
{
    "errorMessage": "[object Object]"
}
```

I would expect to see my error there instead of the `"errorMessage": "[object Object]"`. I've tried explicitly setting the `{error: {contentType: "application/json"}}` when I define the method (although I think that should be the default), but I get the same result.

Do I need to build a specific error object or is this a problem in Claudia? I couldn't find anything in the docs or example projects that demonstrated returning a complete error object.

**Comment by gojko** [comment]
I just double-checked this (https://github.com/claudiajs/claudia-api-builder/blob/master/src/api-builder.js#L107) and this is a Lambda issue, not in Claudia. Whatever you throw as the error, the API Builder just passes on to Lambda. I think Lambda just expects a string or a JS exception object, you might try throwing an `Error` instead of a complex object.

**Comment by thadd** [comment]
Thanks for the quick response. Looking at the lambda docs, it appears that the only way to respond with complex body is to use a success response with a custom status code (e.g. 500). I'll see if I can figure out how to do that with `api.ApiResponse`. Thanks!

**Comment by thadd** [comment]
Never mind that attempt. [This thread](http://stackoverflow.com/a/33522444) indicates it's probably not possible.

**Comment by gojko** [comment]
Lambda is very limited in error responses, it's best if you can pass a string there, so run JSON.Stringify on the object before sending it back
