### ISSUE TITLE
Claudia - custom stage name and domain

### ISSUE THREAD

**Issue by ranlandau** [claudiajs/claudia#48]
Hi,

When i create a claudia project,
1. I wish to change stage name to /v1 - instead of /latest
2. i wish to determine (since i have custom url which is api.XXX.com) the XXX. before - how?
and how to api map it?

**Comment by gojko** [comment]
1. use --version v1 when you do claudia update or claudia create
2. I have no idea what you mean by XXX. You can map the API to it using ApiGateway Custom domains (http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html)

**Comment by naguibihab** [comment]
@gojko seeing that I create the API using claudia, is there a way I can connect my custom domain to that API in the `claudia create` script?

**Comment by gojko** [comment]
@naguibihab please use <https://gitter.im/claudiajs/claudia> for questions, we use github issues only for bugs
