### ISSUE TITLE
Question: Authenticating API endpoint

### ISSUE THREAD

**Issue by ygrenzinger** [claudiajs/claudia#49]
Hello,

Is it possible to put authentication in front of the API ?
I would like to use oauth maybe with a lib like passport (http://passportjs.org/docs/overview) but maybe it's not so easy. So if you have any alternative roads :)

There is a 'boilerplate' repo for doing it directly with Serverless. Can it be an inspiration ?

Thanks for your answer ! 

BTW so far, Claudia seems a great tool to use AWS lambda

**Comment by gojko** [comment]
you should be able to use Cognito from AWS. Claudia will supply the cognito IDs with the request. Check out https://github.com/claudiajs/claudia-api-builder#the-request-object for more info on the request object.

**Comment by ygrenzinger** [comment]
Thanks !

**Comment by gojko** [comment]
if you get stuck somewhere because claudia isn't creating the right template, let me know what you'd like to create and we can integrate it. I haven't used Cognito with Api Gateway, so it might be possible that something isn't covered by Claudia yet

**Comment by daveroberts** [comment]
The request object documentation seems to have been moved here: https://github.com/claudiajs/claudia-api-builder/blob/master/docs/api.md
