### ISSUE TITLE
shelljs vs fs

### ISSUE THREAD

**Issue by fearphage** [claudiajs/claudia#5]
Any reason you're using `shelljs` over `fs`?

For instance, you're using `shelljs.ls(...)` instead of `fs.readdirSync(...)`? Is there a reason for that or merely an oversight? I was working on a PR to resolve this, but I wanted to make sure I wasn't missing something first.

**Comment by gojko** [comment]
this depends on which instance of usage you're referring to, but shelljs.ls is significantly more than just fs.readdirsync. it does multiple parameters, recursive listing and globbing. the two functions are the same only if you are using a single parameter, and that is a directory. eg `fs.readDirSync('*.js')` doesn't work, but `shelljs.ls('*.js')` works perfectly.

**Comment by fearphage** [comment]
I understand that one is not a drop-in replacement for the other and that was merely one example. My question is would you be open to a PR using `fs` where it applies?

**Comment by gojko** [comment]
if it's just cosmetic, then probably not. if you can demonstrate that it does something substantial (eg improve performance, simplify processing), then yes.
