### ISSUE TITLE
Get RequestId

### ISSUE THREAD

**Issue by daarond** [claudiajs/claudia#52]
Easy question: I'm trying to get the current RequestId that corresponds to CloudWatch logging.

Cheers,
Daaron

**Comment by gojko** [comment]
if you're not using the api builder, just get it from the [lambda context object](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html). if you're using the API builder, there's no direct way to do that now, but I can add it.

**Comment by daarond** [comment]
Hi Gojko,
I'm trying to use the API builder, so I would appreciate the addition.
Thanks for all your work on the project!

A few more feature requests:
On Windows 10, the package.json-indicated path doesn't recurse and my
resulting set of files is about 9MB. It would be great if it could recurse
and package up to s3. I'm doing it by hand that way now, but it would be
great if claudia could do it. I'd be happy to pitch in if you could provide
some suggestions about where you think it should go and how it should be
structured.

Cheers,
Daaron

**Comment by gojko** [comment]
Hi,

I just published `claudia-api-builder` 1.3.0, that exposes the lambda context. Check out the [Web Api Lambda Context](https://github.com/claudiajs/example-projects/tree/master/web-api-lambda-context) example project to see it in action.

Regarding the file recursion, I'm not sure I understand the problem.  In general, claudia follows standard NPM packaging rules -- excludes stuff from .gitignore etc and if the files property is set in package.json, it should copy and include that. If that's not what is happening, please open another issue with the details of your package.json and what is not being packaged correctly, so we can deal with that.
