### ISSUE TITLE
Please stop with the spam

### ISSUE THREAD

**Issue by andreis** [claudiajs/claudia#53]
I sometimes get mass emails from repos I starred, but rarely two. Please stop with the spam.

<img width="1092" alt="screen shot 2016-06-30 at 13 03 49" src="https://cloud.githubusercontent.com/assets/1249760/16486170/25741102-3ec3-11e6-90d3-8a48facb6d27.png">

**Comment by gojko** [comment]
this doesn't come from us. I have no idea who Octavia is and why she is talking to you, but nothing to do with us. I suggest reporting this to github support

**Comment by andreis** [comment]
That sounds very creepy; thanks for your reply. I starred the repo again. :) 👍 

*please delete this line once you read it* The sender's address is octavia@buddy.works

**Comment by stojanovic** [comment]
Thanks @andreis. My suggestion is to report that email as a spam.
