### ISSUE TITLE
Support for Node v6?

### ISSUE THREAD

**Issue by FGRibreau** [claudiajs/claudia#55]
Maybe Claudia could reuse Apex way of shiming to support Node v6 in AWS Lambda?
I started [an issue there too](https://github.com/apex/apex/issues/493) and still hesitating to use Claudio or Apex for that (context: we have a NodeJS v6 project to try on AWS Lambda)

**Comment by gojko** [comment]
a core design idea of Claudia is to avoid too much magic, so introducing a Node version that is not supported by AWS is pretty far on the scale of things I don't really want to do. Once AWS supports Node 6, Claudia will as well.

**Comment by FGRibreau** [comment]
I understand your logic @gojko, no problem :)

**Comment by bnolan** [comment]
Node 6 is now [supported](https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/) by lambda - what's the correct way to tell claudia to use the node 6 runtime?

**Comment by gojko** [comment]
@bnolan https://claudiajs.com/news/2017/03/22/node-6-claudia-2.10.0.html
