### ISSUE TITLE
Support authorizationType: 'AWS_IAM'

### ISSUE THREAD

**Issue by cbumgard** [claudiajs/claudia#56]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour: API Gateway endpoints defined by API Builder can be set to Authorization Type 'AWS_IAM' or 'NONE'

* What actually happens: They are hardcoded to 'NONE'

* Link to a minimal, executable project that demonstrates the problem: Project is proprietary, you can look directly at the Claudia code to see where there is a TODO to fix this bug: [https://github.com/claudiajs/claudia/search?utf8=%E2%9C%93&q=authorizationtype](https://github.com/claudiajs/claudia/search?utf8=%E2%9C%93&q=authorizationtype)

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by gojko** [comment]
@cbumgard this should not be a difficult change. would you like to implement it and submit a PR? I could guide you through that.

**Comment by cbumgard** [comment]
Sure, I'd be happy to. How do you see the auth type getting set in the
client code? I would assuming in API builder calls that define the methods,
as some methods will require auth type none while some will require aws_iam.

**Comment by gojko** [comment]
I propose adding that as a config for the request handler. This should be quite similar to how ApiKeyRequired is used. 

Check out this test: https://github.com/claudiajs/claudia/blob/master/spec/rebuild-web-api-spec.js#L313

The code for apiKeyRequired is in these two lines: 
https://github.com/claudiajs/claudia/blob/master/src/tasks/rebuild-web-api.js#L227
https://github.com/claudiajs/claudia/blob/master/src/tasks/rebuild-web-api.js#L116

that should be more or less everything you need to set the right flag and test it. I'm not sure if any additional config is then required for the handlers but api builder will pass on the authentication info in the request object automatically. see https://github.com/claudiajs/claudia-api-builder/blob/master/docs/api.md#the-request-object

**Comment by cdock1029** [comment]
Can "invoke with caller credentials" be supported here as well? 

See https://github.com/awslabs/aws-apigateway-importer/issues/125

**Comment by gojko** [comment]
@cdock1029 the original change for this issue is now merged. If you want to add additional support for caller credentials, go ahead and submit a new PR

**Comment by dhackner** [comment]
I'm looking to add User Pool authentication as well here; I've made the necessary change to allow for CUSTOM or COGNITO_USER_POOLS but I'm wondering if the underlying AWS.apiService doesn't yet support it?

**Comment by gojko** [comment]
@dhakner custom authorizer support is coming in a day or two, I'm cleaning it up now. Regarding cognitive pools, I don't know, never used that. If you made that work, please submit a PR and a test case

**Comment by dhackner** [comment]
I started writing it and then saw your branch :-). I'll add it based off of your work and then just rebase once you've merged your WIP.

**Comment by gojko** [comment]
@dhackner it's now merged into master, I plan to add a few more validation tests and then work on the api builder side of things. so you can fork master now and change stuff, it won't change much

**Comment by dhackner** [comment]
👍

**Comment by dhackner** [comment]
Mind adding an example invocation to the README or example project?

**Comment by gojko** [comment]
@dhackner example invocation of what?
