### ISSUE TITLE
The default API Gateway setup don't include the raw body of a POST

### ISSUE THREAD

**Issue by fczuardi** [claudiajs/claudia#58]
* Expected behaviour:

It should be possible to use claudiajs (and caudia-api-builder) to deploy lambdas that expects the raw body of a POST request in a parameter. 

* Use case:

An use case for this is the signature verification on a Facebook Messenger Bot for example, that sends a signature for the raw body + a secret in the header (see https://developers.facebook.com/docs/messenger-platform/webhook-reference#security )

* What actually happens:

The Body Mapping Template used by claudia is the one at https://github.com/claudiajs/claudia/blob/master/json-templates/apigw-params.txt that does not include the raw body, and the CLI don't have an option to override that template with a different one.

* Workaround

Either manually add the patch on the body mapping template at AWS website:

```
...
  "rawBody": "$util.escapeJavaScript($input.body).replace("\'", "'")",
...
```

Or patch the apigw-params.txt manually.

**Comment by gojko** [comment]
what is the content type that you are using? The raw body is already included for form posts, check https://github.com/claudiajs/claudia/blob/master/json-templates/apigw-params.txt#L37 -- the api gateway templates are selected based on content type, not HTTP method

**Comment by fczuardi** [comment]
application/json is what Facebook sends
On Jul 28, 2016 1:33 AM, Gojko Adzic <notifications@github.com> wrote:what is the content type that you are using? The raw body is already included for form posts, check https://github.com/claudiajs/claudia/blob/master/json-templates/apigw-params.txt#L37 -- the api gateway templates are selected based on content type, not HTTP method

**Comment by gojko** [comment]
Hi,

If you want to add a PR for this, go ahead and I'll merge it. 

The test for it should be something very similar to https://github.com/claudiajs/claudia/blob/master/spec/rebuild-web-api-spec.js#L255,
and the extra line should probably go with the "else" processing for JSON, in https://github.com/claudiajs/claudia/blob/master/json-templates/apigw-params.txt#L41 -- please use a string with quotes inside for testing (API GW has a bug with escaping JS with quotes, which is why the `.replace("\'", "'")` is necessary.

**Comment by fczuardi** [comment]
cool! I'll do it.

Do you think it is ok just to add a new "rawBody" parameter regardless, or should we limit this just for some particular cases, for example: if the header contains an x-hub-signature property?

In other words, would having a property with the full raw body on application/json mappings be useful for other use cases?

**Comment by gojko** [comment]
I wouldn't count on just facebook needing this, so adding rawBody for application/json in general would be my preferred option.

**Comment by fczuardi** [comment]
I've copy/pasted the previous test, hope it's ok :-P
