### ISSUE TITLE
Support add event DynamoDB to lambda

### ISSUE THREAD

**Issue by barhoumio** [claudiajs/claudia#59]
Hi guys,
Thank you for this awesome project.
It seems that claudia not support the dynamodb event.
Is this feature in the ToDO list or not.
Thanks btw.

**Comment by gojko** [comment]
please don't use github issues for questions. if you want to submit a pull request to support this, please do through github; otherwise, use [gitter](https://gitter.im/claudiajs/claudia) chat.
