### ISSUE TITLE
support STS assumed identity

### ISSUE THREAD

**Issue by gojko** [claudiajs/claudia#63]
rebuildWebApi retrieving ownerId doesn't work for assumed roles, needs to use `sts.getCallerIdentity()` instead

**Comment by gojko** [comment]
fixed in `1.6.1`

**Comment by beeva-franciscocalle** [comment]
Hi @gojko I'm trying to figure out how to use the assumed identity but I cannot find how. Could you please give me some hints? Thanks in advance.

**Comment by gojko** [comment]
@beeva-franciscocalle please open a different issue with the exact details of the error you're getting. If Claudia logs anything to the console, the last logged message would also be great.
