### ISSUE TITLE
Path parameters not populated when creating method

### ISSUE THREAD

**Issue by mchristopher** [claudiajs/claudia#65]
* Expected behaviour:

When creating or updating an API method in API Gateway, the `requestParameters` object will be populated with a correct list of parameters. This is required if you use the gateway cache feature in order to allow `cacheKeyParameters` to be set on the Method Integration.

It may also be worth populating `cacheKeyParameters` with all path-based request parameters by default, but that is a feature request, not a bug.

* What actually happens:

The object is omitted.

* Steps to reproduce the problem:

Deploy the [web-api](https://github.com/claudiajs/example-projects/tree/master/web-api) sample, then query the API Gateway `GetMethod` endpoint for anything with a dynamic path parameter. `requestParameters` is expected to have `"requestParameters": {"method.request.path.name": true}`, but is blank.

**Comment by gojko** [comment]
forcing the cache of key parameters makes a big assumption that caching is valid there, so I would definitely not force it, but you're welcome to submit a PR where this can be activated for a method in the request handler args.

regarding the request parameters being populated, claudia doesn't use request models in the API gateway, but instead uses a generic mapping template, so nobody needed these parameters so far.

If you need this feature, the best thing would be to add it would be somewhere around [here](https://github.com/claudiajs/claudia/blob/master/src/tasks/rebuild-web-api.js#L247). I'm not sure if I understand correctly what you need, but it's likely that this should also involve passing the path into `createMethod`, so you can decompose it into generic arguments and assign to the parameters. the path is available in the [`configurePath` function](https://github.com/claudiajs/claudia/blob/master/src/tasks/rebuild-web-api.js#L334), and you can pass it on to `createMethod` from there.

**Comment by gojko** [comment]
i'll close this due to lack of activity. if anyone wants to pick it up later, please reopen the issue
