### ISSUE TITLE
STS support for deploy

### ISSUE THREAD

**Issue by beeva-franciscocalle** [claudiajs/claudia#68]
* **Expected behaviour**:
It should create and deploy both the Api Gateway endpoint and the Lambda function

* What actually happens:
I get an `AccessDenied` error due to the restrictions our operations operations team imposes. Here is the output

```
initialising IAM role	iam.createRole	RoleName=claudia-hello-world-executor
{ [AccessDenied: User: arn:aws:iam::XXXXXXXXX:user/francisco.calle is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::XXXXXXXXX:role/claudia-hello-world-executor]
  cause:
   { [AccessDenied: User: arn:aws:iam::XXXXXXXXX:user/francisco.calle is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::XXXXXXXXX:role/claudia-hello-world-executor]
     message: 'User: arn:aws:iam::XXXXXXXXX:user/francisco.calle is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::XXXXXXXXX:role/claudia-hello-world-executor',
     code: 'AccessDenied',
     time: Thu Sep 15 2016 17:41:22 GMT+0200 (CEST),
     requestId: 'da51dd6d-7b5a-11e6-acfe-07a6295c8f0a',
     statusCode: 403,
     retryable: false,
     retryDelay: 78.65617338102311 },
  isOperational: true,
  code: 'AccessDenied',
  time: Thu Sep 15 2016 17:41:22 GMT+0200 (CEST),
  requestId: 'da51dd6d-7b5a-11e6-acfe-07a6295c8f0a',
  statusCode: 403,
  retryable: false,
  retryDelay: 78.65617338102311 }
```
* Link to a minimal, executable project that demonstrates the problem: No need, I'm just using the hello world example

* Steps to reproduce the problem: 
Execute `claudia --role-arn arn:aws:iam::XXXXXXXXX:role/dev-project-delegated-developer --role-arn-name corp-session-default --profile corp-session-default create --region us-east-1 --api-module index`

* Extra information: 
I've made a repo based on another project to deploy a lambda function that illustrates how we have to make the deployments https://github.com/beeva-franciscocalle/beeva-aws-node-lambda

**Comment by gojko** [comment]
Hi,

neither `--role-arn` and `--role-arn-name` are claudia arguments, not sure where you got that info. You can use --role, to specify an existing role name that will be assigned to the Lambda function instead of creating a new one. That's not the STS role you're using to access AWS, it is the role assigned to your function.

You'll have to set up the STS role and role name in your profile or environment variables, and then just call `claudia create`. 

For a detailed list of claudia create args, check out https://github.com/claudiajs/claudia/blob/master/docs/create.md

**Comment by beeva-franciscocalle** [comment]
> neither --role-arn and --role-arn-name are claudia arguments, not sure where you got that info
I was trying to adapt claudia to our deployment process so I modified the code just to give a try based on the module [I pointed out](https://github.com/beeva-franciscocalle/beeva-aws-node-lambda)

> You'll have to set up the STS role and role name in your profile or environment variables, and then just call claudia create.
That was what I did in the beginning. I've got my credential in my `~/.aws/crendentials` file and executing `AWS_PROFILE=corp-session-default claudia --profile corp-session-default create --region us-east-1 --api-module index` still gets the same error.

As far as I ~~know~~ discovered ( yesterday to be more precise 😆 ), to create the Lambda I need to pass the credentials for the role creating the elements (I'm required to use an specific role for that) so I have to do it this way:

```node
lambda = new AWS.Lambda({
    region: config.region,
    accessKeyId: '<value of the result of assuming the role>',
    secretAccessKey: '<value of the result of assuming the role>',
    sessionToken: '<value of the result of assuming the role>'
});
```

Either way, I don't want to bother you - you've just done a great great job 👍  - so I'll try to hack claudia to adapt to the way our company requires.

**Comment by gojko** [comment]
I think you should be just able to put those in environment variables, Node.js AWS SDK will pick it up from there. You don't need to hack claudia at all, it will just use the standard Node.js AWS SDK authentication.

**Comment by beeva-franciscocalle** [comment]
Yes, you're totally right. But it's not working. I'm having a look on what the hell is going on. I've modified `cmd.js` in line 47 with two `console.log` to print the shared info just to check if it's working. This is the output:

```
> args.profile: corp-session-default
> AWS.config.credentials SharedIniFileCredentials {
  expired: false,
  expireTime: null,
  accessKeyId: '---------',
  sessionToken: '---------',
  filename: '/-------/.aws/credentials',
  profile: 'corp-session-default',
  disableAssumeRole: false }
```
(just removed the values to clarify and security 😉 )

Apparently, everything is working just fine but still got the `AccessDenied`

**Comment by beeva-franciscocalle** [comment]
Ok, just made it work. Still don't know it's not working but ... 

This is the modifications I've made to the `cmd.js` to make it work:

```
if (args.profile) {
  AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: args.profile});
}

var asumeRoleParams = {
  RoleArn: args['role-arn'], /* required */
  RoleSessionName: args['role-arn-name'], /* required */
}

var sts = new AWS.STS();
var request = sts.assumeRole(asumeRoleParams);
request
  .on('success', function(response) {
    console.log('🙈  roles assumed!');
    AWS.config.credentials.accessKeyId = response.data.Credentials.AccessKeyId;
    AWS.config.credentials.secretAccessKey = response.data.Credentials.SecretAccessKey;
    AWS.config.credentials.sessionToken = response.data.Credentials.SessionToken;

    commands[command](args, logger).then(function (result) {
      if (result) {
        console.log(JSON.stringify(result, null, 2));
      }
      process.exit();
    }, function (e) {
      console.error(e);
      process.exit(1);
    });
  })
  .on('error', function(response) {
    console.error('🔥🔥🔥🔥', response);
  })
  .send();
```

I know it's not pretty code but it just works. My first guess goes to the `SharedIniFileCredentials` that it's not retrieving the `sessionToken` (which is in the `~/.aws/credentials` file).

**Comment by gojko** [comment]
i'd expect that you can use the assumed role without having to modify claudia code at all. check out this for details on how to set up the access privileges: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

**Comment by beeva-franciscocalle** [comment]
Mee too. Really. 

It's really weird because unless I explicitly assign the result of the `sts.assumeRole` like this

```node
AWS.config.credentials.accessKeyId = response.data.Credentials.AccessKeyId;
AWS.config.credentials.secretAccessKey = response.data.Credentials.SecretAccessKey;
AWS.config.credentials.sessionToken = response.data.Credentials.SessionToken;
```

the deployment process fails (AccessDenied).

**Comment by gojko** [comment]
are you setting session token in the environment variables? (what is the value of your AWS_SESSION_TOKEN env variable?)

**Comment by beeva-franciscocalle** [comment]
> check out this for details on how to set up the access privileges:

This is my current config
```
$ ll ~/.aws
total 16
-rw-------  1 francisco.calle  staff    43B 29 jun 13:23 config
-rw-------  1 francisco.calle  staff   904B 16 sep 13:12 credentials

$ cat ~/.aws/credentials
[default]
aws_access_key_id = XXXXXXXXX
aws_secret_access_key =XXXXXXXXX
region = eu-west-1

[corp-session-default]
aws_access_key_id = XXXXXXXXX
aws_secret_access_key = XXXXXXXXX
aws_session_token = XXXXXXXXX
aws_security_token = XXXXXXXXX
region = eu-west-1
```

**Comment by gojko** [comment]
I also found this gem, it might help: http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

**Comment by beeva-franciscocalle** [comment]
> are you setting session token in the environment variables?

yep I tried every possible way [stated in the doc](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Setting_AWS_Credentials) 

1 Loaded from IAM roles for Amazon EC2 (if running on EC2),
2 Loaded from the shared credentials file (~/.aws/credentials),
3 Loaded from environment variables,
4 Loaded from a JSON file on disk,
5 Hardcoded in your application

A variation of the 5th one is the only working one so far.

> I also found this gem, it might help: http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

I'll give it a shot and keep you posted!

Again, thanks for the support.

**Comment by briancsparks** [comment]
Assuming you have IAM roles setup properly, [https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html) gives most of the info. The trick is to use the AWS CLI (aws sts assume-role ...) to assume the right role, but then you have to manually stuff the credentials into environment variables.

```
aws sts assume-role --role-arn arn:aws:...:role/supercow --role-session-name foobar > /tmp/creds
export AWS_SECRET_ACCESS_KEY="$(cat /tmp/creds | jq '.Credentials.SecretAccessKey')"
# similar for AWS_ACCESS_KEY_ID and AWS_SESSION_TOKEN

rm -f /tmp/creds

# Claudia is now happy
claudia create ...

```

With `~/.aws/config` similar to:

```
[profile claudia]
aws_access_key_id = ABC123
aws_secret_access_key = adsfger1243

[profile xaccount]
role_arn = arn:aws:...:role/supercow
source_profile = claudia
```

**Comment by LukeMizuhashi** [comment]
I can't easily add a command line JSON parser to my environment, but I do have node. So, I wrote a quick script to assume a role via STS and then set credentials in environment variables:

https://github.com/LukeMizuhashi/assume-aws-environment-variables


Using that, I'm able to use Claudia to manage resources in AWS Organization accounts--assuming IAM is already set up to let my CLI profile assume roles with sufficient privileges in those accounts.

**Comment by adrai** [comment]
Just to share how I'm using claudia in combination with aws organization accounts:
I use https://github.com/adrai/aws-auto-assume-role a node.js only solution.
In my deploy script in my package.json there is something like this:
`AWS_PROFILE=my-aws-profile node -r aws-auto-assume-role ./node_modules/.bin/claudia update --version dev`
