### ISSUE TITLE
Support Custom Authorizer

### ISSUE THREAD

**Issue by sakae-nakajima** [claudiajs/claudia#7]
I'd be great if we could configure custom [authorizer](http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html).

BTW, this project is awesome!

**Comment by gojko** [comment]
I have no experience with custom authorizers, so I wouldn't know where to start, but this looks as a nice thing to implement. Do you want to give it a shot and then submit a pull request? if you'd like to chat about this, find me at https://gitter.im/claudiajs/claudia

**Comment by gojko** [comment]
i'm closing this due to lack of response; if anyone wants to pick this up in the future, please reopen the issue.

**Comment by cevatkerim** [comment]
it seems like adding it wouldn't require too much change based on what I'm seeing when I export the api gateway configuration. 
I don't have much experience using the sdk for this but here is an example:

for the endpoint:

`"security": [
          {
            "custom_Auth": []
          }
        ]`

and add the definition:
`"securityDefinitions": {
    "custom_Auth": {
      "type": "apiKey",
      "name": "auth",
      "in": "header",
      "x-amazon-apigateway-authtype": "custom"
    }
  }`

**Comment by Luiz-N** [comment]
+1

**Comment by gojko** [comment]
this is now possible (with claudia 1.7.1, and claudia api-builder 1.6.0)

```js
api.registerAuthorizer('myAuth', {lambdaName: 'some-lambda-name'});
```

then you can just specify it as an authorizer in a method:

```js
api.get('/', function (r) {/* some processing */ }, { customAuthorizer: 'myAuth' })
```

Check out the [docs](https://github.com/claudiajs/claudia-api-builder/blob/master/docs/api.md#using-custom-authorizers) for more info, and the [custom authorizers example](https://github.com/claudiajs/example-projects/tree/master/custom-authorizers) for a working example
