### ISSUE TITLE
Cannot find module 'api-builder'

### ISSUE THREAD

**Issue by bitIO** [claudiajs/claudia#71]
Following the tutorial at https://claudiajs.com/tutorials/hello-world-api-gateway.html

I've got this error message:

```
{"errorMessage":"Cannot find module 'claudia-api-builder'","errorType":"Error","stackTrace":["Function.Module._load (module.js:276:25)","Module.require (module.js:353:17)","require (internal/module.js:12:17)","Object.<anonymous> (/var/task/app.js:1:80)","Module._compile (module.js:409:26)","Object.Module._extensions..js (module.js:416:10)","Module.load (module.js:343:32)","Function.Module._load (module.js:300:12)","Module.require (module.js:353:17)"]}
```

I've checked the zip folder generated and it contains the module. Any clue on what can be happening?

**Comment by gojko** [comment]
Hi,

please use the gitter channel for general questions, issues are for reporting bugs only.

https://gitter.im/claudiajs/claudia

paste your source code there, so we can look at it together
