### ISSUE TITLE
Include directory not juste files

### ISSUE THREAD

**Issue by denneulin** [claudiajs/claudia#76]
I am creating a package with claudia create.
My project have files separated in folders so I add this folders to the package.json files entry.
Claudia creates the package with the files but they are at root level instead of being in their specific folders.

* Expected behaviour: keep directory hierarchy

* What actually happens: files inside a directory are moved at root level instead of being in a directory

* Steps to reproduce the problem:
create a directory `toto` with a file `a.js`
add a `files` entry into package.json and add the directory
the package created by claudia has the file `a.js` but it is at project root level and not in `toto` directory.

**Comment by gojko** [comment]
can you paste your package.json here?

**Comment by gojko** [comment]
fixed by https://github.com/claudiajs/claudia/commit/fc0eabe9e0efe88b709b3fd00249b4bd6a379dc3, will be part of the next release
