### ISSUE TITLE
The option `use-s3-bucket` does not work in the region `eu-central-1`.

### ISSUE THREAD

**Issue by ncochard** [claudiajs/claudia#83]
The option `use-s3-bucket` does not work in the region `eu-central-1`.

When I execute the following command:

	claudia create --region eu-central-1 --api-module xxx --use-s3-bucket my-bucket-name

I get the following error:

	InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

This issue is discussed on [stackoverflow](http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4).

> AWS4-HMAC-SHA256, also known as Signature Version 4, ("V4") is one of two authentication schemes supported by S3.
> 
> All regions support V4, [...].

One solution may be to change the source code of ClaudiaJS as followed. If my understanding is correct, this will work in any region. However, could this modification cause some issues to anyone who is already using ClaudiaJS on an existing project?

	new aws.S3({signatureVersion: 'v4'})

I tried to run the following command, but that does not fix the issue. 

	aws configure set default.s3.signature_version s3v4

Any guidance would be welcome.

Regards

**Comment by gojko** [comment]
I'll add that and retest. it seems as something that should be backwards compatible, so if it does not cause problems, we'll put that in

**Comment by ncochard** [comment]
Awesome.
Thanks

**Comment by gojko** [comment]
try 2.1.4 from NPM, it has the fix you suggested. I can't create a bucket in eu with my account so I can't really test it.

**Comment by gojko** [comment]
should be fixed by https://github.com/claudiajs/claudia/commit/e8b6181ce4a90f42ac837ce8625b016351a132c8

**Comment by ncochard** [comment]
I just tested this. It works fine.
Thanks, Gojko
