### ISSUE TITLE
Long running task (120sec +) gets called multiple times with test-lambda

### ISSUE THREAD

**Issue by leoalves** [claudiajs/claudia#85]
If I have a long running task 120 secs +  and execute it with claudia test-lambda. The call gets executed  multiple times, every 120 secs. If I execute it directly in the aws console, it gets timed out according to the  lambda configuration timeout and only gets executed once.

Ex: executed claudia test-lambda at 12:00
the same call gets executed again at 12:02
again at 12:04
again at 12:06 ...
The console just hangs there and after 10 minutes or so report a network error. And the same script got called 5 times.

Not sure if the 120 seconds is related to when I initially created the lambda. But I created it with the following command:
claudia create --name blablab --region us-east-1 --role blablabla --timeout 120 --handler main.handler
and changed the timeout to 300 in the aws console.

I didn't find anywhere in the claudia code where this timeout is set. And it is not saved in the claudia.json config. 

Here is a code example to reproduce the issue
```
function timeoutPromise () {
  return new Promise((resolve, reject) => {
    var executionTime = 0
    function wait1sec () {
      setTimeout(() => {
        executionTime = executionTime + 1
        if (executionTime > 700) {
          resolve('waited 700 secs')
        } else {
          console.log('waited: ' + executionTime + ' secs')
          wait1sec()
        }
      }, 1000)
    }
    wait1sec()
  })
}


exports.handler = (event, context) => {
  'use strict'
  timeoutPromise()
  .then((res) => {
    context.succeed(res)
  })
  .catch((err) => {
    context.fail(err)
  })
}
```

If you look at the cloudwatch log. It will show the script executed multiple times with a 2 minute difference between each

It probably doesn't need to be a promise. I did as a promise because the code where I found the issue was a promise.  

I updated to the latest claudia on npm.  claudia@2.1.4. And was able to reproduce the issue with this script.

Thanks

**Comment by gojko** [comment]
this is due to how it gets invoked. request-reply invocations do not retry, and event invocations retry on error. You can add a new arg to test-lambda to do request/response invocation if you like and submit a PR. Alternatively, just use `aws lambda invoke` from the command line and set the invocation type. Check out http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestSyntax
