### ISSUE TITLE
Claudia Facebook Bot Language Issue

### ISSUE THREAD

**Issue by topcoderme** [claudiajs/claudia#87]
2016-12-04T15:58:32.411Z	816c0bde-ba3a-11e6-9071-9bf49512c9e9	[Error: Language you selected does not exists, please select the other one]

This happens everytime I send a message to my Fb Page. 
I followed the following tutorial word to word.
https://aws.amazon.com/blogs/compute/create-and-deploy-a-chat-bot-to-aws-lambda-in-five-minutes/

**Comment by gojko** [comment]
this is an issue with huh, that was changed after the article was published. remove huh with your own message and it will work

**Comment by stojanovic** [comment]
`huh` is fixed so that example should work fine now
