### ISSUE TITLE
"Role with name [my name]-executor already exists" on error

### ISSUE THREAD

**Issue by marcusoftnet** [claudiajs/claudia#9]
I ran: 

`claudia create --name storingInDynamo --region us-west-2 --api-module index`

but forgot the `files` property. That trigger an excellent error message: `package.json does not contain the files property`

Great - but when I fixed that and ran the create-command again: 

```javascript
{ [EntityAlreadyExists: Role with name storingInDynamo-executor already exists.]
  cause: 
   { [EntityAlreadyExists: Role with name storingInDynamo-executor already exists.]
     message: 'Role with name storingInDynamo-executor already exists.',
     code: 'EntityAlreadyExists',
     time: Fri Feb 26 2016 14:24:46 GMT+0100 (CET),
     requestId: '4df7b6fb-dc8c-11e5-9b40-35d169b930d8',
     statusCode: 409,
     retryable: false,
     retryDelay: 72.52002414315939 },
  isOperational: true,
  code: 'EntityAlreadyExists',
  time: Fri Feb 26 2016 14:24:46 GMT+0100 (CET),
  requestId: '4df7b6fb-dc8c-11e5-9b40-35d169b930d8',
  statusCode: 409,
  retryable: false,
  retryDelay: 72.52002414315939 }
```

And now I don't know how to fix this, except updating the name of the function (`--name`)

**Comment by gojko** [comment]
I'm planning to add a cleanup function soon. meanwhile, go to the aws web console (aws.amazon.com), select IAM, then Roles, then delete the role. Alternatively, delete the role from the command line using [the aws cli](http://docs.aws.amazon.com/cli/latest/reference/iam/delete-role.html)

**Comment by marcusoftnet** [comment]
Thanks!

**Comment by venuv** [comment]
Hi, a newbie question. 
i'm getting the authorization error (below) upon trying to deploy a lambda function as outlined in https://blog.jayway.com/2016/11/06/introduction-to-claudia-js/.

what do I need to do in the IAM in terms of creating roles and assigning to users? 
thanks.venu
----
> claudia create --region eu-east-1 --api-module index
initialising IAM role	iam.createRole	RoleName=claudia_test-executor
{ AccessDenied: User: arn:aws:iam::456689991567:user/xxxx is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::456689991567:role/claudia_test-executor

**Comment by thom-nic** [comment]
Did this cleanup function ever get implemented?  calling `aws iam delete-role ` is not so simple because you have to delete the inline `log-writer` policy first.  So it seems you have to do 
```
aws iam delete-role-policy --role-name my-function-executor --policy-name log-writer
aws iam delete-role --role-name my-function-executor
```

**Comment by simalexan** [comment]
@thom-nic its best to ask and discuss this on the gitter. please, if its not too much of a hassle, write it down on gitter and we can have a discussion on that

**Comment by cameronoxley** [comment]
Was there any resolution on this?

**Comment by thom-nic** [comment]
TBH I don't remember. I probably deleted everything on the AWS/IAM side and started fresh.  Unfortunately Gitter sucks as a searchable knowledge base so here we are :(

I think the steps I listed above are sufficient to get everything cleaned up but I haven't needed to do it in a while so I don't recall.

**Comment by alpha-beta-soup** [comment]
Hmm, deleting the role in IAM doesn't seem to be sufficient — I still get the error after doing so. Using the CLI has the same outcome. Is there something else that needs deleting?
