### ISSUE TITLE
API builder example with promises

### ISSUE THREAD

**Issue by ile** [claudiajs/claudia#91]
Hi,

As it seems that promises are the way to make a more complex API builder apps, why not create an example for that?

It took quite a while for me to understand that I need to use promises in the first place. There was [this](https://claudiajs.com/tutorials/hello-world-api-gateway.html), but where should I have gotten the info that promises are needed to make the route handler to have asynchronous handling? I think this needs to be clarified in those basic examples...

Thanks.

**Comment by gojko** [comment]
please don't use github issues for general discussion. use the [gitter channel](https://gitter.im/claudiajs/claudia) instead

**Comment by ile** [comment]
It was an issue.
