### ISSUE TITLE
[TypeError: undefined is not a function] on 'claudia update'

### ISSUE THREAD

**Issue by bautrey** [claudiajs/claudia#92]
I'm following along on the simple helloworld tutorial at https://aws.amazon.com/blogs/compute/how-to-turn-node-js-projects-into-aws-lambda-microservices-easily-with-claudiajs/.

Everything works great initially.  Then I add the second "greet" resource using the superb module carefully copying everything correctly.  Then I issue the 'claudia update' command as instructed and it deletes the original resource (hello) or existing resources ('hello' and 'greet'):

updating REST API	apigateway.deleteResource	resourceId=h68nfg	r
updating REST API	apigateway.deleteResource	resourceId=uros7f	r
 
Then tries to issue the command:

updating REST API	apigateway.setAcceptHeader

then gives the error:

[TypeError: undefined is not a function]

And leaves the helloworld api with no resources (there were deleted).

If I delete all three elements (helloworld api in API Gateway, helloworld-executor role in IAM, and helloworld function in Lambda), delete claudia.json, and run 'claudia create --region us-east-1 --api-module app' again then everything sets up just fine.

There is only an issue on 'claudia update' and, as far as I know, just on this tutorial as I haven't tried others.

**Comment by gojko** [comment]
thanks for reporting this. Can you just please let me know which version of claudia and api builder you installed? (try `claudia -v` or just paste the versions from `package.json`)

**Comment by gojko** [comment]
also, which version of node.js are you running (`node --version`)? I just tried going through the process you described and everything deployed correctly, so it might be an environment issue

**Comment by bautrey** [comment]
I'm sorry for the unnecessary question... my version of node.js was out of date.  Thank you for your help and doing great work.
