### ISSUE TITLE
Claudia behind the proxy

### ISSUE THREAD

**Issue by olifer** [claudiajs/claudia#97]
The command `claudia create` returns an error when is running from the machine which is behind the proxy.

**Example command**: create --region eu-west-1 --handler lambda.handler 
**Result**:
```
initialising IAM role   iam.createRole  RoleName=claudia-test-executor
{ Error: connect ETIMEDOUT 52.94.225.3:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  message: 'connect ETIMEDOUT 52.94.225.3:443',
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '52.94.225.3',
  port: 443,
  region: 'us-east-1',
  hostname: 'iam.amazonaws.com',
  retryable: true,
  time: 2017-02-03T18:05:54.774Z }
```
(Environmental variables are set, aws cli works without issues, appropriate permissions are given to an aws user that is used)

**Comment by gojko** [comment]
Hi,

Claudia uses the AWS SDK for Node.js, which should officially work with the HTTP_PROXY env variable. If not, that's a bug for them really, not for us.

However, if you want to help by creating a new option for Claudia, eg `--proxy`, that would be great. I don't have a proxy to do this, but if you'd like to fix & test it and submit a PR, I'll merge it. The change is most likely going to be something similar to this line. 

https://github.com/claudiajs/claudia/blob/786603b140be8909a8db6dd5bbc17202e09aa1f3/bin/cmd.js#L50
